package org.ikasan.studio.generator;

import com.intellij.openapi.project.Project;
import com.intellij.psi.PsiJavaFile;

import java.util.HashMap;
import java.util.Map;

/**
 * Currently both velocity and embedded strategy are being evaluated
 */
public class ApplicationTemplate extends Generator {
    public static final String APPLICATION_CLASS_NAME = "Application";
    private static final String APPLICATION_VM = "ApplicationTemplate.vm";
    private static final String APPLICATION_CLASS_IMP =
            "/**\n" +
            " * This is the Spring book start class.\n" +
            " * This file is auto-generated by Ikasan Studio, do no edit..\n" +
            " */\n" +
            "@org.springframework.boot.autoconfigure.SpringBootApplication " +
            "public class Application { public static void main(String[] args) {" +
            "org.springframework.boot.SpringApplication.run(Application.class, args);}}";

    public static PsiJavaFile createApplication(final Project project) {
        String templateString = "";
        if (GENERATOR_STRATEGY == GeneratorStrategy.VELOCITY) {
            templateString = generateContents();
        } else {
            templateString = APPLICATION_CLASS_IMP;
        }
        return createTemplateFile(project, DEFAULT_STUDIO_PACKAGE, APPLICATION_CLASS_NAME, templateString, true, true);
    }

    public static String generateContents() {
        Map<String, Object> configs = new HashMap<>();
        configs.put(CLASS_NAME_TAG, APPLICATION_CLASS_NAME);
        return VelocityUtils.generateFromTemplate(APPLICATION_VM, configs);
    }
}

