package org.ikasan;

/**
* The component factory defines the details of the components and their configuration.
*
* This file is auto-generated by Ikasan Studio, do no edit.
*/
@org.springframework.context.annotation.Configuration
public class ComponentFactoryMyFlow1
{
@org.springframework.beans.factory.annotation.Value("${module.name}")
private String moduleName;
    /** Development-only override supplied by Studio's local SFTP harness. External configuration stays unchanged. */
    private static <T> T studioLocalSftp(T endpoint, String flow, String component, boolean consumer) {
        if (!Boolean.getBoolean("studio.test.sftp.enabled")) return endpoint;
        try {
            Object configuration = endpoint.getClass().getMethod("getConfiguration").invoke(endpoint);
            String directory = "flow-" + java.net.URLEncoder.encode(flow, java.nio.charset.StandardCharsets.UTF_8)
                    + "/component-" + java.net.URLEncoder.encode(component, java.nio.charset.StandardCharsets.UTF_8);
            // Flow startup reloads persisted configuration. Give the local run a separate ID so
            // external server settings cannot overwrite these values, or be overwritten by them.
            endpoint.getClass().getMethod("setConfiguredResourceId", String.class).invoke(endpoint,
                    "studio-test-sftp-" + System.getProperty("studio.test.sftp.session") + "-" + directory);
            java.nio.file.Path home = java.nio.file.Path.of(System.getProperty("studio.test.sftp.home"));
            java.nio.file.Files.createDirectories(home.resolve(directory));
            studioSftpSetting(configuration, "RemoteHost", String.class, "127.0.0.1");
            studioSftpSetting(configuration, "RemotePort", Integer.class, Integer.valueOf(System.getProperty("studio.test.sftp.port")));
            studioSftpSetting(configuration, "Username", String.class, "ikasan");
            studioSftpSetting(configuration, "Password", String.class, System.getProperty("studio.test.sftp.password"));
            studioSftpSetting(configuration, "PrivateKeyFilename", String.class, "");
            studioSftpSetting(configuration, "PrivateKeyPassphrase", String.class, "");
            studioSftpSetting(configuration, "KnownHostsFilename", String.class, System.getProperty("studio.test.sftp.knownHosts"));
            studioSftpSetting(configuration, "PreferredKeyExchangeAlgorithm", String.class, null);
            studioSftpSetting(configuration, consumer ? "SourceDirectory" : "OutputDirectory", String.class, "/" + directory);
            if (consumer) studioSftpSetting(configuration, "MinAge", Long.class, 0L);
            return endpoint;
        } catch (Exception failure) {
            throw new IllegalStateException("Cannot configure local test SFTP server for " + flow + " / " + component, failure);
        }
    }
    private static void studioSftpSetting(Object configuration, String name, Class<?> type, Object value) throws Exception {
        configuration.getClass().getMethod("set" + name, type).invoke(configuration, value);
    }

@javax.annotation.Resource
org.ikasan.builder.BuilderFactory builderFactory;

@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.consumer.clientID}")
java.lang.String myFlow1SftpConsumerClientID;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.consumer.cron-expression}")
java.lang.String myFlow1SftpConsumerCronExpression;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.consumer.filename-pattern}")
java.lang.String myFlow1SftpConsumerFilenamePattern;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.consumer.known-hosts-filename}")
java.lang.String myFlow1SftpConsumerKnownHostsFilename;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.consumer.max-retry-attempts}")
java.lang.Integer myFlow1SftpConsumerMaxRetryAttempts;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.consumer.move-on-success-new-path}")
java.lang.String myFlow1SftpConsumerMoveOnSuccessNewPath;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.consumer.password}")
java.lang.String myFlow1SftpConsumerPassword;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.consumer.preferred-key-exchange-algorithm}")
java.lang.String myFlow1SftpConsumerPreferredKeyExchangeAlgorithm;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.consumer.private-key-filename}")
java.lang.String myFlow1SftpConsumerPrivateKeyFilename;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.consumer.remote-host}")
java.lang.String myFlow1SftpConsumerRemoteHost;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.consumer.remote-port}")
java.lang.Integer myFlow1SftpConsumerRemotePort;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.consumer.source-directory}")
java.lang.String myFlow1SftpConsumerSourceDirectory;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.consumer.username}")
java.lang.String myFlow1SftpConsumerUsername;
@javax.annotation.Resource
org.ikasan.endpoint.sftp.consumer.SftpConsumerConfiguration myConfigurationClass;
@javax.annotation.Resource
org.ikasan.spec.event.EventFactory orgIkasanMyflowMyEventFactory;
@javax.annotation.Resource
org.ikasan.spec.event.ManagedEventIdentifierService myManagedEventIdentifierServiceClass;
@javax.annotation.Resource
org.ikasan.component.endpoint.quartz.consumer.MessageProvider myMessageProviderClass;
@javax.annotation.Resource
org.ikasan.framework.factory.DirectoryURLFactory myDirectoryURLFactoryClass;
@javax.annotation.Resource
org.springframework.transaction.jta.JtaTransactionManager myTransactionManagerClass;

public org.ikasan.spec.component.endpoint.Consumer getMySFTPConsumer() {
return studioLocalSftp(builderFactory.getComponentBuilder().sftpConsumer()
.setAgeOfFiles(10)
.setChecksum(true)
.setChronological(true)
.setChunkSize(1048577)
.setChunking(true)
.setCleanupJournalOnComplete(true)
.setClientID(myFlow1SftpConsumerClientID)
.setConfiguration(myConfigurationClass)
.setConfiguredResourceId("myUniqueConfiguredResourceIdName")
.setConnectionTimeout(600001)
.setCriticalOnStartup(true)
.setCronExpression(myFlow1SftpConsumerCronExpression)
.setDestructive(true)
.setEager(true)
.setEventFactory(orgIkasanMyflowMyEventFactory)
.setFilenamePattern(myFlow1SftpConsumerFilenamePattern)
.setIgnoreMisfire(true)
.setIsRecursive(true)
.setKnownHostsFilename(myFlow1SftpConsumerKnownHostsFilename)
.setManagedEventIdentifierService(myManagedEventIdentifierServiceClass)
.setMaxEagerCallbacks(1)
.setMaxRetryAttempts(myFlow1SftpConsumerMaxRetryAttempts)
.setMaxRows(11)
.setMessageProvider(myMessageProviderClass)
.setMinAge(12L)
.setMoveOnSuccessNewPath(myFlow1SftpConsumerMoveOnSuccessNewPath)
.setPassword(myFlow1SftpConsumerPassword)
.setPreferredKeyExchangeAlgorithm(myFlow1SftpConsumerPreferredKeyExchangeAlgorithm)
.setPrivateKeyFilename(myFlow1SftpConsumerPrivateKeyFilename)
.setRemoteHost(myFlow1SftpConsumerRemoteHost)
.setRemotePort(myFlow1SftpConsumerRemotePort)
.setRenameOnSuccess(true)
.setRenameOnSuccessExtension("newExtension")
.setSourceDirectory(myFlow1SftpConsumerSourceDirectory)
.setSourceDirectoryURLFactory(myDirectoryURLFactoryClass)
.setTransactionManager(myTransactionManagerClass)
.setUsername(myFlow1SftpConsumerUsername)
.build(), "MyFlow1", "My SFTP Consumer", true);
}}