package org.ikasan.studio.boot;

/**
* The module config class defines details of the modules and identifies the flows but should not contain details
* of the components in each flow.
*
* This file is auto-generated by Ikasan Studio, do no edit.
*/
@org.springframework.context.annotation.Configuration("ModuleFactory")
@org.springframework.context.annotation.ImportResource({
"classpath:h2-datasource-conf.xml",
"classpath:ikasan-transaction-pointcut-ikasanMessageListener.xml"
})
public class ModuleConfig {
@org.springframework.beans.factory.annotation.Value("${module.name}")
private String moduleName;

@javax.annotation.Resource
org.ikasan.builder.BuilderFactory builderFactory;
@javax.annotation.Resource
org.ikasan.studio.boot.flow.myflow1.MyFlow1 myFlow1;

@org.springframework.context.annotation.Bean
public org.ikasan.spec.module.Module myModule()
{
org.ikasan.builder.ModuleBuilder moduleBuilder = builderFactory.getModuleBuilder(moduleName)
.withDescription("My first module");

org.ikasan.builder.component.ComponentBuilder componentBuilder = builderFactory.getComponentBuilder();

org.ikasan.spec.module.Module module = moduleBuilder
.addFlow(myFlow1.getMyFlow1())
.build();
return module;
}

}