package org.ikasan.studio.core.generator;

import com.fasterxml.jackson.core.JsonProcessingException;
import org.ikasan.studio.core.StudioBuildException;
import org.ikasan.studio.core.metapack.ComponentLibrary;
import org.ikasan.studio.core.metapack.model.ComponentMeta;
import org.ikasan.studio.core.metapack.model.ComponentPropertyMeta;
import org.ikasan.studio.core.persistence.json.StudioJson;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Generates the local, tool-neutral contract used by coding assistants working in a Studio project. */
public final class AiProjectContractGenerator {
    public static final String CONTRACT_VERSION = "1";

    private AiProjectContractGenerator() { }

    public static String agentsGuide() {
        return """
                # Ikasan Studio agent instructions

                These instructions apply to Ikasan applications generated by the Studio archetype.
                When this file is viewed inside the Ikasan Studio source repository, it is template
                content, not instructions for developing the plugin; use the repository-root `AGENTS.md`
                for plugin development.

                When Studio is open, its live in-memory model is authoritative. If the Studio MCP bridge is
                connected, use studio_snapshot, studio_catalogue and studio_propose, then check studio_proposal_status.
                Validated supported changes can apply automatically unless Confirm deletes requires review (enabled by default for deletions and replacements) or Always ask for approval is enabled or developer-owned code could be replaced.
                Ask the developer to Apply only when the status is awaiting_review; wait for applied before continuing. Never edit model.json behind an open Studio.
                If MCP is unavailable, use the proposal-file workflow in generated/IKASAN_STUDIO.md. Read the
                saved model, calculate its SHA-256, and write a uniquely named .studio-proposal.json file in
                the project-root ai-proposals/ folder. Write to a temporary file first, then rename it into
                place when complete. New proposal files can apply automatically under the same setting and user-code protection;
                confirm the saved model reflects the change before continuing. For proposals awaiting review,
                ask the developer to click Review on the AI proposal ready notification,
                or Tools -> Review Latest AI Proposal, then Apply. Keep IntelliJ and Studio open; no MCP connection or direct model edit is needed.
                After Studio confirms application, read the updated model and generated files, then compile
                and test. Do not treat writing a proposal file as applying the change. If the installed Studio
                lacks the import action, prepare the proposal and ask the developer to update Studio or make
                the change in its properties UI; do not bypass this by editing the active model on disk.

                For file proposals, always read `<proposal-filename>.result.json` beside the submitted file
                and match its proposalSha256 before continuing. Follow the recovery/status instructions in
                generated/IKASAN_STUDIO.md; never assume writing a proposal applied it.

                This project is managed by Ikasan Studio. Before editing `generated/src/main/model/model.json`,
                read `generated/IKASAN_STUDIO.md` and
                `generated/src/main/model/component-catalogue.json`.

                `model.json` is the version-neutral source of truth. Make minimal changes, preserve unknown
                fields, validate the result, and let Ikasan Studio regenerate its owned files. Do not directly
                edit files under `generated/` other than `model.json`. Developer-owned implementations belong
                under `user/`. When the requested task includes working behaviour, completing a newly generated,
                unmodified stub for that task is authorised; use focused edits and tests. Inspect the file and
                its diff first. Preserve existing developer logic and ask before replacing it or regenerating
                its implementation. If ownership or intent is unclear, ask rather than assume a file is a stub.
                For functional flow, integration or demonstration requests, aim for working behaviour unless
                the user explicitly asks for a diagram or skeleton. Choose and state simple sample behaviour for
                underspecified demos; ask about material business or destination decisions. Complete unblocked
                implementation and tests even when external services are unavailable. Verify required Spring
                beans against real code/configuration, not just model references. Never claim an implementation
                exists without locating it. A generated class or completed diagram is not proof of working behaviour.
                Verify the normal Studio Run module experience as well as test launchers. ESB flows, including demos,
                must stay running and accept later work after sample input is exhausted; idle is not stopped.
                Finite completion is allowed only for explicitly requested batch examples or bounded tests.
                Keep normal ESB flows AUTOMATIC; report missing external setup without hiding startup failures.
                **DEMO ACCEPTANCE RULE: DO NOT LEAVE DEMO FLOWS STOPPED.** While the module is running,
                every requested normal demo flow must run and remain ready for later input. A stopped flow does
                no work. Quietly disabling it hides missing setup and makes developers waste time finding why
                nothing happens; a visible startup error exposes the problem. Do not call the demo complete
                while any required flow is stopped or in error, even if that state is explained in a README.
                Resolve the cause or report the demo as BLOCKED/INCOMPLETE with the exact remaining action.
                Before every task needing test settings, reread LOCAL_TEST_ENVIRONMENT.md in the project root.
                For local FTP/SMTP, read the Studio local test harnesses section in generated/IKASAN_STUDIO.md.
                A closed port may mean the developer has not started the harness; ask for that startup step.
                Accept a simple name=value block: supplied values override selected catalogue defaults. Blank
                or omitted optional settings keep existing values on existing components, defaults on new ones,
                or remain unset if no default exists. Ask only for missing required details, not every property.
                Filled-in local settings need no READY flag. Respect explicit NOT_CONFIGURED/NOT_USED statuses.
                Local test passwords may be supplied literally and used in the necessary Studio proposals/model
                configuration; do not echo them in chat or logs. Environment references are optional and need
                supported runtime binding, not literal copying of env: names into properties. Use key filenames,
                never private-key contents. sftp.directory / ftp.directory map to producer outputDirectory and
                consumer sourceDirectory; confirm an existing server-visible directory. Choose one supported
                authentication mode, check conditional requirements, and preserve applicable optional defaults.
                Follow the requested test scope and preserve unrelated data. Verify actual delivery and continued
                readiness, not just compilation. This guidance permits the developer's literal local-test values
                even if an older generated guide/skill suggested credential references only. Preserve this file;
                if absent, Studio creates a template during project onboarding or generation.
                For building, changing, troubleshooting or reviewing Studio application flows, read
                .agents/skills/ikasan-integration-workflow/SKILL.md when present and use its workflow.
                Clients with skill discovery may select ikasan-integration-workflow automatically; otherwise
                read the file explicitly. Review-only tasks remain read-only. The skill supplements these
                instructions and the current generated contract; it does not grant extra permissions.
                Follow the completion
                checklist and demo guidance in generated/IKASAN_STUDIO.md; report unfinished implementations
                and unsupported components explicitly.
                """;
    }

    public static String studioGuide(String metapackVersion) {
        return """
                # Working with Ikasan Studio using an AI coding assistant

                This is an offline contract for both developers and coding agents. It does not require an MCP
                server, network access, or an external AI service. The selected meta-pack is `%s`.

                ## Sources of truth

                - `src/main/model/model.json` (relative to this generated module) is the editable Studio model.
                - `src/main/model/model.schema.json` describes its stable JSON shape.
                - `src/main/model/component-catalogue.json` is generated from the selected meta-pack and lists
                  valid component keys, roles, properties, defaults, types and choices.
                - Java, Maven and configuration files in `generated/` are Studio-owned derived output.
                - Files in `user/` are developer-owned. Complete newly generated, unmodified stubs when working
                  behaviour is part of the requested task; preserve existing logic and confirm before replacing it.

                ## Integration workflow skill

                For building, changing, troubleshooting or reviewing Studio application flows, read
                .agents/skills/ikasan-integration-workflow/SKILL.md when present and use its workflow.
                Clients with skill discovery may select ikasan-integration-workflow automatically; otherwise
                read the file explicitly. Review-only tasks remain read-only. The skill supplements these
                instructions and the current generated contract; it does not grant extra permissions.

                The project-local skill and Claude discovery entry are created only if missing. Existing
                customisations are preserved. Skill loading depends on the AI client; a model name alone does
                not establish skill support. Clients with file access can read the shared SKILL.md directly.

                ## Local test configuration

                Before every task needing test settings, reread LOCAL_TEST_ENVIRONMENT.md in the project root.
                For local FTP/SMTP, read the Studio local test harnesses section in generated/IKASAN_STUDIO.md.
                A closed port may mean the developer has not started the harness; ask for that startup step.
                Accept a simple name=value block: supplied values override selected catalogue defaults. Blank
                or omitted optional settings keep existing values on existing components, defaults on new ones,
                or remain unset if no default exists. Ask only for missing required details, not every property.
                Filled-in local settings need no READY flag. Respect explicit NOT_CONFIGURED/NOT_USED statuses.
                Local test passwords may be supplied literally and used in the necessary Studio proposals/model
                configuration; do not echo them in chat or logs. Environment references are optional and need
                supported runtime binding, not literal copying of env: names into properties. Use key filenames,
                never private-key contents. sftp.directory / ftp.directory map to producer outputDirectory and
                consumer sourceDirectory; confirm an existing server-visible directory. Choose one supported
                authentication mode, check conditional requirements, and preserve applicable optional defaults.
                Follow the requested test scope and preserve unrelated data. Verify actual delivery and continued
                readiness, not just compilation. This guidance permits the developer's literal local-test values
                even if an older generated guide/skill suggested credential references only. Preserve this file;
                if absent, Studio creates a template during project onboarding or generation.

                Review and update LOCAL_TEST_ENVIRONMENT.md as a developer startup task. Add
                /LOCAL_TEST_ENVIRONMENT.md to the root .gitignore before filling it with machine-specific
                settings; Studio leaves existing ignore rules unchanged. Presence or READY status does not grant
                extra permissions or guarantee availability. Check service health and report prerequisites.
                The file is guidance, not an executable script or automatically loaded application config.

                ## Understanding and researching Ikasan

                Ikasan is a Java enterprise integration platform (ESB). A module contains flows; a consumer
                receives events, processing components transform/filter/route them, and producers deliver results.
                Builders wire the components into flows. Transactions, recovery, exclusion and replay determine
                what happens when delivery fails. The module-local Blue Console and central Dashboard have
                different roles; they are not interchangeable names for the same application.

                Official framework source: https://github.com/ikasanEIP/ikasan
                Studio plugin source: https://github.com/ikasanEIP/IkasanStudio
                These repositories serve different purposes: use framework source for runtime API behaviour and
                the project catalogue/Studio instructions for supported design operations.

                Read ikasanVersion and frameworkReference in component-catalogue.json (or studio_catalogue).
                Start with the exact releaseSource URL when supplied, not the repository's default branch.
                Studio currently bundles Ikasan 3.3.9 (Java 11) and 4.1.6 (Java 17). The 3.x, 4.x and 5.x
                families must not be treated as API-compatible; 5.x is not currently a bundled Studio target.
                The project POM/BOM and resolved dependencies identify the actual runtime, including overrides.
                Check namespaces, signatures, property defaults and lifecycle semantics against that version.
                Do not infer a framework version from an arbitrary custom meta-pack ID, or invent a release tag.

                At the selected release, navigate these paths (layout can vary between releases):
                - README.md and QuickOverview.md: introduction and links to developer/component/service guides.
                - ikasaneip/spec: public component and flow interfaces; start here for method contracts.
                - ikasaneip/component: implementations and component README files; endpoints, converters,
                  routers and filters. Follow the implementingClass from the catalogue to its source file.
                - ikasaneip/builder and component-factory: builder methods and component construction.
                - ikasaneip/flow and module: execution, event handling, flow states and module lifecycle.
                - ikasaneip/recovery-manager, exclusion, hospital and replay: exception actions, retries,
                  rejected-event handling and replay. Inspect actual action implementation and tests.
                - ikasaneip/sample: runnable examples for wiring, transport settings and custom components.
                - ikasaneip/documentation: ArchitectureGuide and ReferenceGuide; also follow README links.
                - UpgradePath.md and release POMs: migration notes and dependency/platform requirements.
                - Relevant src/test directories: examples of successful behaviour, failures and lifecycle rules.

                Research narrowly: locate the exact class, read its interface, implementation and nearby tests,
                then check a sample using it. Cite the release/path or Maven coordinates supporting a non-obvious
                API decision. Do not clone/build the whole framework merely to inspect one method. Repository
                examples explain APIs; they do not override Studio ownership rules or the user's requirements.
                Keep framework source read-only unless the user explicitly requests framework changes.

                If browsing is unavailable, inspect matching sources attached in IntelliJ or cached Maven
                *-sources.jar files for the resolved dependency version. Maven's local repository is commonly
                ~/.m2/repository but may be configured elsewhere. Inspect the dependency tree and overrides;
                if source is unavailable, inspect the resolved class signatures/bytecode (e.g. javap) and state
                the remaining uncertainty. Fetch sources only when network access is permitted. These links
                provide directions, not browsing permissions. Never substitute a different major version silently.

                ## Component guidance and implementation ownership

                Read each component's helpText (which may contain HTML), documentation reference, payload
                contracts, completionChecks and property help. beanRequirement explains the evidence needed
                for a userSuppliedClass reference. These are obligations, not proof of generated behaviour.
                The catalogue's proposalOperations and proposalSupport explain
                what the AI bridge can configure; presence in the catalogue alone does not imply support.
                Endpoints are associated visual/configuration elements, not independent flow processors.

                generatesUserImplementedClass means Studio may create a class in user/; it does not mean
                that class implements the requested behaviour. Check requiresStub, userImplementedClassName
                and the generated Java. A selected conversion recipe can supply an implementation, whereas
                a generic Converter may only contain UnsupportedOperationException. Other scaffolds may
                return a constant, pass data through, or do nothing: successful compilation is not sufficient.
                Property flags userSuppliedClass, protectFromOverwrite, noStubRequired and
                affectsUserImplementedClass distinguish bean references, protected implementations and
                generation-sensitive configuration. A noStubRequired reference needs an existing configured
                bean; do not create a stub merely because a property is marked userSuppliedClass.

                Inspect user/ files and existing diffs before editing. A request for working functionality
                authorises focused implementation of newly generated, unmodified stubs for that task.
                It does not authorise replacing existing developer logic or enabling Studio's overwrite flag.
                Make Java implementation edits in user/ using the AI client's normal code-editing tools;
                use Studio proposals for model changes. Preserve Spring bean names, interfaces and method
                signatures. If code is already customised or intent is uncertain, ask before replacing it.

                ## Proposal names

                New flow and component names must match [A-Za-z][A-Za-z0-9_ ]{0,79}: start with a letter, then letters, digits, spaces or underscores, maximum 80 characters. For numbered flows use Flow01 or Demo01, never a leading number. Existing flow/component references must use their exact saved names.

                ## Defaults and model property changes

                A catalogue default is a literal value; defaultExpression is an internal derivation rule,
                not a Java class name or a value to copy into a proposal. Omit derived properties on creation
                and let Studio resolve them, or provide explicit, meaningful Java class names. Different
                implementations in the same flow need distinct class names. Display renaming does not rename
                an existing implementation class. Check setPropertySupported and editGuidance before editing:
                addComponent/replaceComponent accept initial implementation settings, but setProperty cannot
                normally change implementation-sensitive properties. Do not repeatedly retry a forbidden edit.
                Exception: an unresolved __fieldName: value in userImplementedClassName can be repaired with
                setProperty and a valid concrete Java class name; this does not rename existing valid classes.

                ## Cross-flow transport connections and ordering

                A producer hands off to a consumer through transport configuration, not a cross-flow connect
                operation. connect only orders components inside one flow route. Plan related flows together and
                add them in the desired canvas order; numbering names does not reorder existing flows. The proposal
                API has no flow-reordering operation: use Studio to reorder existing flows, never delete and
                recreate them just to change their position.

                - JMS: match destinationJndiName, connectionFactoryName, connectionFactoryJndiPropertyProviderUrl
                  and pubSubDomain. Check the broker, JNDI factory, message type, autoContentConversion and trusted
                  object packages as well. Matching labels alone do not prove messages can be delivered.
                - FTP/FTPS: match protocol/security mode, host, port and producer outputDirectory to consumer
                  sourceDirectory. Match generated filenames to the consumer filenamePattern, and verify
                  credentials, permissions, polling and post-consumption handling. File-transfer recipes default to
                  unique .dat filenames when no input filename or recipeFilename is supplied; a .txt-only
                  consumer will miss them. A fixed recipeFilename can collide on repeated deliveries. A custom source directory
                  factory may change the actual location. Avoid endless reprocessing or overwriting files.
                - SFTP: apply the same directory/filename checks with SSH authentication and host-key validation.
                  SFTP is a separate protocol from FTP/FTPS. Studio currently draws shared-endpoint connectors
                  for JMS and FTP/FTPS, not SFTP; matching SFTP configuration still permits a runtime hand-off.
                Shared-endpoint lines indicate inferred configuration matches, not verified delivery. Check
                payload types at both ends and report external services still needing setup or runtime tests.

                ## Generation failures and recovery

                Model application and Java generation are separate outcomes. After every proposal, wait for
                generation to finish before dependent work. A generation_failed status or Studio error is a
                real failure, not a routine progress message to ignore until all proposals finish. Stop dependent
                submissions, inspect the error, reread the current model/revision, and prepare a focused repair
                using supported operations. Do not resubmit the whole creation batch into an already updated model.
                For file proposals, recompute the saved model SHA-256 and use a new proposal filename.
                Tell the developer whether you are repairing the failure or need their action; do not ask them
                to click Apply unless Studio actually requires review. Verify that expected flow factories and
                user classes exist after successful generation. Compiling an old skeleton does not validate new
                flows. Keep compilation, runtime delivery and visual coverage claims separate.

                ## Payload examples and recipe selection

                Copy all three properties from recipeConfigurations into the converter proposal:
                conversionRecipeId, fromType and toType. For addComponent, omitted types are filled from the
                selected recipe. Explicitly supplied types must match. Editing an existing component does not
                silently change its types; supply all required property changes in the same proposal.
                Use recipeConfigurations as ready-to-use property examples, and read the corresponding
                conversionRecipes entry for preconditions and configuration. Match the entire source and
                target type, including collection element types and the meta-pack's javax/jakarta namespace.
                Never fix a rejected recipe by merely removing its ID and then claiming the converter is done.
                Either choose a matching recipe or implement and test the custom conversion in user/.

                - Local File Consumer emits List<File>. Default List Splitter emits individual File values.
                  After splitting, a File-to-String converter must read each file using an explicit charset
                  (for example UTF-8: a file containing hello produces the String hello). Test read failures.
                  single-local-file-to-string instead accepts List<File> containing exactly one file; it is
                  not suitable after a splitter, or for silently ignoring the rest of a batch.
                - JMS Message-to-ObjectMessage is a type check, not a universal cast. A custom converter
                  must accept an ObjectMessage and reject other message kinds with a clear transformation
                  failure. Test an ObjectMessage and a non-object message. Use the selected meta-pack's
                  interfaces and catalogue recipes; do not mix javax.jms and jakarta.jms.
                - A Translator changes a mutable payload in place. Use a Converter when replacing a value
                  such as String. Give filters, brokers, splitters and producers actual demonstration
                  behaviour and tests rather than leaving their default pass-through or no-op scaffolds.

                ## Demonstration scope and completion checklist

                For requests to build a flow, integration or demonstration, aim for working behaviour by default.
                Stop at a diagram or scaffolding only when the user explicitly requests that scope. Do not choose
                visual-only scope merely because it is easier or external services are unavailable. Complete the
                locally implementable behaviour and tests, then report the remaining external setup separately.
                For underspecified demonstrations, choose simple, deterministic sample behaviour and state your
                assumptions (for example a sample order with fixed fields). Ask only when a missing decision
                materially changes the required behaviour, destination, data ownership or safety. Do not invent
                production business rules, credentials or permission to send messages to real external systems.
                For an every-component request, compare the selected catalogue's component keys with the
                resulting model. Include supported routers and explicit exception policies when requested; report
                associated endpoints separately from executable components. Do not omit missing work silently.

                ESB lifecycle requirement: flows are long-lived services, including demonstration flows.
                **DEMO ACCEPTANCE RULE: DO NOT LEAVE DEMO FLOWS STOPPED.** While the module is running,
                every requested normal demo flow must run and remain ready for later input. A stopped flow does
                no work. Quietly disabling it hides missing setup and makes developers waste time finding why
                nothing happens; a visible startup error exposes the problem. Do not call the demo complete
                while any required flow is stopped or in error, even if that state is explained in a README.
                Resolve the cause or report the demo as BLOCKED/INCOMPLETE with the exact remaining action.
                After a sample batch, they must remain running and ready for later input. An unexplained Stopped
                state is a failed acceptance check even if the first batch was delivered. Stop only for an explicit
                operator action, application shutdown or a configured failure policy; an explicitly requested
                finite batch is an exception, not the default. Do not reclassify unintended stopping as success
                by documenting it in a README or adding a completion notification.

                An Event Generating Consumer terminates when its provider returns null: null is not an idle signal.
                Do not exhaust a short list and return null in a normal ESB demo. Prefer scheduled, polling or
                listener-based input with correct idle behaviour. Where catalogue coverage needs an Event
                Generating Consumer, use its built-in provider unless the requested behaviour requires a custom
                payload provider. Add a paced provider only when the developer explicitly requests one; catalogue
                coverage alone does not require it. Custom consumers/providers must honour cancellation and the
                selected framework version's lifecycle contract. Verify rollback, interruption, stop/start and
                worker cleanup. Never fake isRunning, swallow failures, busy-spin or flood logs/messages just to
                keep the display green. Give repeated events distinct IDs unless deliberately testing replay.
                Keep bounded fixtures in automated tests; tests should stop the application during teardown,
                rather than making the normal application self-terminate after its fixtures.

                Acceptance check: observe successful delivery, allow an idle interval, assert that each ready
                flow remains running, then send another batch through the same running application and verify
                delivery without resetting a bean, restarting the flow or restarting the application. If a paced
                generator was explicitly requested, observe at least two separated batches and continued readiness.
                Verify that exclusion
                or another recoverable policy does not stop the flow and that subsequent valid input is processed.

                When missing external configuration blocks part of the brief, finish independent paths and
                ask a focused question listing the exact remaining settings. Maintain a requested-versus-delivered
                inventory; do not silently narrow an every-component request to the currently convenient types.
                Do not replace a requested transport with a scheduled reminder and logging producer just to
                obtain a Running state. A reminder is not an SFTP/FTP implementation or component coverage.
                Retain real requested transport components where validation permits; otherwise report the
                blocked design explicitly and ask for the required settings before claiming completion.
                Offer a clearly labelled incomplete design only if Studio's validation permits it; do not invent
                credentials or claim unavailable transports are configured. Explain how to complete and test them.
                Keep normal ESB flows AUTOMATIC, including paths whose external services are unavailable.
                Do not set MANUAL or DISABLED to suppress startup errors or make a partial demo appear healthy.
                Resolve supplied configuration and service issues within the authorised scope; otherwise report
                the exact blocker and ask for the missing setup. Do not invent credentials or destinations.
                Startup/error states must remain visible and count as incomplete acceptance checks. Only change
                a flow to MANUAL or DISABLED when the developer explicitly requests it; preserve existing
                operator choices. Existing database startup
                controls may override new properties: inspect the effective runtime setting and use supported
                operator controls. Do not globally force allowDbOverwrite or erase runtime data to conceal this.

                For each requested functional path:
                1. Confirm Studio applied the model and generation completed; reread the saved model and files.
                2. Inspect the relevant user/ classes for throwing stubs, TODO implementations, constant dummy
                   results and no-op methods. Implement the required behaviour within the ownership rules above.
                   Explanatory TODO comments alone do not prove that a component is unfinished.
                3. Trace a representative payload from consumer through every transformation to producer and,
                   where applicable, the receiving flow. Check payload types, actual output values, filename
                   filters and transport settings. Locate every required implementation and Spring bean in code
                   or dependency configuration: a model reference or successful compilation is not evidence that
                   a bean exists. Check its type, registration, name/qualifier and component-scan coverage.
                   If a required custom bean was not generated, inspect the selected version's interface and
                   create the missing implementation and registration in user/ within the requested scope.
                   Do not create competing beans or replace existing implementations. For external noStubRequired
                   beans, verify the actual configured provider rather than inventing a placeholder.
                4. List external requirements: input files/directories, FTP/SFTP servers, JMS brokers, SMTP,
                   databases and credentials as applicable. Prefer supported local test facilities for demos,
                   verify they are configured, and never claim that an unavailable service was exercised.
                5. Compile and run relevant tests, including representative success and failure payloads.
                   If authorised to run the module, verify startup and sample messages; otherwise report that
                   runtime behaviour remains unverified. Do not send real external messages without authorisation.
                6. Report model application, implementation, compilation, tests and runtime verification
                   separately. Cite the actual implementation files and test results supporting completion.
                   A build with no tests only proves compilation; do not call it behaviour verification.
                   List incomplete classes, unsupported components and remaining setup explicitly. Continue
                   implementing unblocked parts rather than treating the list of gaps as task completion.

                ## Efficient implementation and verification

                Before constructing several related flows, read LOCAL_TEST_ENVIRONMENT.md once for this task
                and check the supplied services needed by the brief. Identify unavailable services early; do
                not repeatedly try the same unavailable endpoint. Keep working on independent requirements.
                Check payload types, mandatory authentication and transaction requirements before submitting
                a coherent proposal. For raw JMS object conversion, validate/narrow Message to ObjectMessage
                before a converter that requires ObjectMessage; match the selected version's JMS namespace.
                For JMS redelivery/exclusion examples, configure the required transactional consumer and verify
                persisted exclusion plus subsequent valid delivery, not only a thrown exception in a unit test.
                For periodic samples, a Scheduled Consumer plus a Converter is usually sufficient. A custom
                messageProvider is also supported: complete its developer-owned invoke(JobExecutionContext)
                method and check the registered bean name rather than replacing the consumer to avoid a stub.

                Verify one representative implementation of each distinct pattern before repeating it. Batch
                related corrections, wait for application/generation results, and rerun affected checks first.
                Once those pass, run one final module-level verification covering all acceptance requirements.
                Repeat broad testing only after changes or new failures justify it. Use bounded waits and stop
                when acceptance evidence is complete; report remaining external setup separately. Do not add
                compiler exclusions or reflection-based lifecycle workarounds just to hide a generator/framework
                defect: identify the cause, prefer supported APIs, and report any necessary workaround explicitly.

                ## Runtime verification of functional paths

                Component tests and an isolated embedded transport test do not exercise the generated application.
                Use staged verification: compilation, component behaviour, generated application startup, then
                end-to-end delivery. Report which stages actually ran; do not infer later stages from earlier ones.
                When local execution is within the user's authorised task, carry out the available stages rather
                than stopping at a recommendation to test. Otherwise provide reproducible commands and prerequisites.

                Start with a self-contained path using local files or an embedded transport, where supported by
                the selected version. Load the actual generated application configuration and flow factories;
                a test that scans only user/ beans does not verify the generated Spring wiring. Check required
                transaction/configuration beans, flow startup state and startup errors. Do not work around wiring
                failures with substitute production beans merely to make a test pass.

                Before launch, inspect every automatically starting flow and its destinations. Report unavailable
                external services and resolve authorised setup without disabling flows. Bounded tests may isolate
                dependencies, but must not change the saved startup policy or substitute for normal-launch
                verification. Never suppress normal startup failures with a profile that disables affected flows.

                Verify the developer's normal launch path as a separate acceptance check: Studio Run module,
                its generated Application entry point, actual profiles, working directory and persisted startup
                controls. A custom launcher that forces every flow MANUAL then starts selected flows verifies
                only that launcher. It does not establish that Run module is ready. If IDE access is unavailable,
                exercise the equivalent launch configuration and explicitly mark the interactive check unverified.
                Compare every flow's expected and observed state after startup and sample delivery; investigate
                unexpected Stopped, error and recovery states. Distinguish deliberate completion, waiting for
                setup and failure. Prefer Studio's supported harnesses or documented local service setup; do not
                hide prerequisites in a test script that the normal launcher never runs. Use free/ephemeral ports
                for isolated tests where configurable; report port conflicts without stopping another project.

                For each paired path, send a distinctive sample through the real sender and receiving flow.
                Assert the expected received value or observable output, not only matching endpoint settings,
                a connector line or a log saying the application started. Use bounded waits and identify the
                failing stage on timeout. Test a relevant rejection/rollback path where applicable. Record the
                working directory, input, expected output and command so the developer can repeat the check.
                Verification must use its own inputs and endpoints. Override saved absolute file paths in the
                test configuration when using a temporary checkout; otherwise the receiver may scan the original
                project while the test writes elsewhere. Assert the effective input location. Prefer portable
                demo paths with an explicit working directory, while keeping SSH identity paths user-specific.

                For file-producing implementations, do not expose a partially written final file. Write and close
                a unique temporary file in the destination filesystem, then publish it using a supported atomic
                operation. Confirm filesystem and concurrent-writer semantics; do not assume ATOMIC_MOVE preserves
                an existing target or silently replace developer files. For remote transfers, inspect the selected
                transport's staging/rename support rather than assuming local filesystem guarantees apply.
                Test interrupted publication and retry, not only duplicate successful writes. Define how matching
                completed output, conflicting output and abandoned temporary files are handled. Keep input eligible
                for retry on failure and distinguish committed delivery from a later input-archiving failure.
                Idempotent filenames alone do not establish crash recovery or exactly-once delivery.

                ## Studio local test harnesses

                Studio provides local FTP and SMTP test servers which the developer starts explicitly in the IDE.
                A closed local port during implementation may simply mean the harness has not been started yet;
                it does not prove the supplied settings are wrong or that infrastructure must be installed.
                Check these settings and the intended harness before changing endpoints or proposing another server.

                - FTP: right-click a supported local FTP Consumer or Producer and select **Start Test FTP Server**,
                  then **Show Test FTP Server Details** for the actual address, credentials and test directory.
                  Use **Show Test FTP Directory** to inspect files. The existing server-visible root is `/`;
                  any different directory must exist inside that root. Do not infer credentials from port numbers.
                - SMTP: right-click an Email Producer or its endpoint and select **Start Test Mail Server**,
                  then **Show Test Mail Server Details** for the SMTP address and web inbox. Studio uses MailHog;
                  the first start may require a download. Check Terminal output/notifications if startup fails.
                - These controls start test servers, not the application. Start the required harnesses before
                  **Run module**. Harness settings/details and supplied values determine ports; do not assume
                  that a listener on a familiar port is the intended server.
                - The FTP harness is plain FTP, not SFTP or FTPS. SFTP needs the configured external/local SSH
                  server. A JMS test reader needs a functioning JMS provider; it does not start a broker.

                If you cannot operate the IDE controls, ask the developer to start the named harness and confirm
                its details. Continue independent implementation, then verify real delivery once it is available.
                Keep demo flows AUTOMATIC: do not disable them because their harness is not running. Report the
                specific harness startup step as pending; do not claim end-to-end verification or demo completion.
                Synthetic message injection does not verify FTP/SFTP acquisition or remote service connectivity.

                For external transports, prefer isolated local test services or the supported Studio harnesses.
                Check protocol, ports, directories, permissions and host-key requirements before delivery tests.
                For bundled FTP harness demos, inspect its details and use the existing session root / for
                both producer and consumer unless a custom subdirectory is actually provisioned. Verify listing,
                write and rename access before starting either flow; a producer's create-directory option is not
                a startup-order guarantee. A failed change-directory operation can mean a missing path, incorrect
                session-root assumption or insufficient permissions, not an empty input queue.
                For SFTP, ask which existing identity to use. Keys commonly live under the module user's home
                .ssh directory, but filenames, formats and server authorization must be confirmed. Use resolved
                paths, not an assumed project-local key or unexpanded ~. Never read private key contents into
                the chat or copy them into the repository. Independently verify the server host fingerprint.
                Distinguish configured, reachable and delivery-tested services. Do not invent credentials or
                bypass SSH/TLS verification. Unavailable services should not block unrelated local verification.
                Stop only test processes started by this task and clean up only its own temporary inputs/outputs.

                Verify shutdown separately from delivery: stop started flows, close the application context and
                wait a bounded time for owned workers and resources to terminate. Where relevant, test stop/start
                on the same consumer instance and ensure no old worker continues delivering after stop returns.
                Observe normal child-process exit from a supervising process. System.exit(0), forced termination
                or an outer timeout is not evidence of clean shutdown. A delivery check may pass while shutdown
                fails; report both results, preserve diagnostics and use a nonzero verification exit status for
                failed assertions or cleanup. Do not hide leaked executors merely to print a successful result.

                End with a compact per-path record: implemented behaviour, tests run, startup/delivery evidence,
                external prerequisites and remaining blockers. Include unsupported catalogue types separately;
                full coverage of proposal-supported types is not full catalogue coverage.

                ## Live Studio workflow

                Use Tools -> Connect AI to Ikasan Studio for IntelliJ MCP or the bundled Java adapter.
                Read studio_snapshot and studio_catalogue, then submit studio_propose with the returned revision
                and structured operations. Studio validates every proposal. Validated supported changes apply automatically
                unless Settings -> Tools -> Ikasan Studio -> Always ask for approval is enabled (default: off),
                or Confirm deletes is enabled (default: on) and the proposal deletes flows/components or replaces components.
                Potential developer-owned code replacement always requires review and Apply. Both routes create one undoable change.
                Check studio_proposal_status: request Apply only for awaiting_review, wait while generating,
                and continue only after applied. Report generation_failed instead of assuming success. If the chat turn ended while
                awaiting review, the developer must tell the AI to continue; Apply does not restart an idle chat.
                While Studio is open, do not edit model.json on disk.

                ## Proposal file workflow (no MCP required)

                After submitting a proposal file, read its adjacent `<proposal-filename>.result.json`.
                Match proposalSha256 to the SHA-256 of the exact proposal bytes before trusting it.
                Status awaiting_review means ask for developer review; generating means wait; applied means
                generation completed and you must now verify the updated files. For rejected, read message,
                current model and catalogue, correct the problem and submit a fresh uniquely named proposal
                with an up-to-date baseModelSha256. Attempt at most two corrections per request, then explain
                the blocker and the Studio UI fallback. For generation_failed, inspect generation diagnostics
                and current model before proceeding: changes may already be present. Respect cancelled/undone;
                do not automatically resubmit. Missing feedback is not success: use Review Latest AI Proposal
                or ask the developer to copy the rejection feedback. Do not poll indefinitely or bypass Studio.

                1. Keep Studio and IntelliJ open. Read the saved model and component catalogue.
                2. Calculate SHA-256 of the exact bytes of generated/src/main/model/model.json, for example
                   `sha256sum generated/src/main/model/model.json`. Do not reformat the model before hashing.
                3. Write a UTF-8 file such as ai-proposals/rename-consumer.studio-proposal.json, outside generated/.
                   Create ai-proposals/ in the project root if needed. Use a new filename for each proposal;
                   preserve previous proposals. Write a temporary file without the .studio-proposal.json suffix,
                   then rename it to the final filename when complete so Studio does not read a partial file.
                   Use this format, replacing the digest and names with values from the current project:

                   ```json
                   {
                     "formatVersion": 1,
                     "baseModelSha256": "<64-character SHA-256 of the saved model>",
                     "operations": [
                       {"type": "renameComponent", "flow": "flow1", "component": "my egc",
                        "name": "EventGeneratingConsumer"}
                     ]
                   }
                   ```

                4. Studio detects new or updated files directly in ai-proposals/. Validated supported proposals can
                   apply automatically unless Confirm deletes requires review (enabled by default for deletions and replacements) or Always ask for approval is enabled or developer-owned code could be replaced. Confirm the saved model has
                   changed before continuing; writing a proposal is never proof of application.
                   Other proposals show AI proposal ready.
                   Ask the developer to click Review on that notification, or Tools -> Review Latest AI Proposal,
                   then review the operations and click Apply. The menu selects the most recently modified file.
                   Existing files do not trigger notifications on IDE restart; use the menu to review them.
                   Tools -> Import AI Proposal into Ikasan Studio remains available for selecting any proposal.
                   Importing does not enable an MCP server or give the AI live access.
                5. Studio checks the digest, compares the saved model with its live design, validates operations,
                   and rejects stale proposals. If rejected, save any intended changes through Studio and prepare
                   a fresh proposal from the updated model. Never edit model.json to make a proposal pass.
                6. After Apply and generation complete, ask the AI to read the updated files and compile/test.
                   A saved proposal file is not an applied change. The model changes support Undo in Studio.

                ## Supported proposal operations

                Both MCP and file proposals use the same operations (1 to 100 per proposal):

                - deleteFlow: type, flow (existing name). Removes the entire flow and its attached test harnesses; retains developer-owned source files.
                - addFlow: type, flow (new name). May create an empty design placeholder; do not invent components.
                  Flows can be built incrementally across proposals. An incomplete flow is a design in progress,
                  not a rejection; it needs a consumer and producer before it can run.
                - addComponent: type, flow, key (exact catalogue key), name, optional properties object and route path.
                  route is an array of branch names, e.g. ["Accepted"] or ["Accepted", "Audit"]. Omit for root.
                - deleteComponent: type, flow, component (current name). Removes only the design component;
                  retains developer-owned source files. Remaining components stay connected within their route. Populated routers cannot be deleted/replaced.
                - replaceComponent: type, flow, component (current name), key (new catalogue key), name,
                  optional properties object. Preserves position; consumers must be replaced with consumers.
                  Uses the new type's defaults plus the supplied properties, not the old type's configuration.
                  Retains developer-owned source files. Prefer this for changing an existing consumer's type.
                - setProperty: type, flow, component (current name), property, value (scalar or null).
                  Protected user-supplied bean references such as endpointEventProvider may refer to existing
                  classes. Implementation regeneration remains a Studio operation.
                - renameComponent: type, flow, component (current name), name (new name).
                  Subsequent operations use the new name. Studio updates route transitions; it does not
                  rename Java implementation classes or edit developer-owned source files.
                - connect: type, flow, optional route path, order (all executable components in that route exactly
                  once; include consumer first only for root). Do not list associated endpoint decorations.
                - setFlowProperty: type, flow, property, value (scalar or null to clear). Keep flowStartupType=AUTOMATIC
                  unless the developer explicitly requests another startup policy. Names, structural fields and implementation properties are excluded.
                - configureRoutes: type, flow, component (router name), names (2 to 32 branch names).
                  Names start with a letter and contain only letters/digits. Retain names of populated branches;
                  empty branches may be changed. Add components to each branch using the route path.
                - setExceptionResolution: type, flow, exception (fully qualified class, optional .class suffix),
                  action (from exceptionActions in the catalogue), optional properties object. Adds or updates
                  the rule for that exception, preserving other rules. Read exact action parameter names/defaults.

                Linear and branched route trees are supported. A router terminates its parent route; each branch
                should end in a producer or another router. Shared downstream merges are not supported.
                Flow renaming and migration still require Studio. Do not alter transitions on disk.

                For routing requests, identify an explicit predicate and named destinations. A Single Recipient
                Router returns exactly one configured route name; a Multi Recipient Router returns a list of
                configured names. Complete the generated user/ logic, preserve existing code, and test each branch,
                fallback and fan-out. Treat shared mutable payloads carefully; do not assume fan-out copies them.
                Configure branch names before implementing the router; later changes require checking its code.

                Exception rules are flow-wide, not ordinary connected processors. Ask for the failure type and
                intended action when business consequences are unclear. Do not silently ignore errors or choose
                infinite retries. For a demonstration, propose an explicit narrowly scoped failure and policy,
                e.g. TransformationException -> excludeEvent, and verify exclusion and later valid delivery.
                Class-name syntax is validated, but compile and test against the selected version to establish
                that the class is a Throwable, which exception the flow resolves, and the actual action taken.
                Use catalogue action guidance: legacy retry property interval is a retry COUNT, not a delay.
                Cron syntax receives a structural check; validate its runtime scheduling meaning in tests.
                Preserve unknown fields; use catalogue keys and property validation rules. Names must be unique
                within their scope, including their generated Java names. Complete flows require a consumer.

                To change Ikasan versions, use Studio's Migrate action. It previews the model, generated
                code and Maven changes and saves a recovery snapshot before applying the conversion.

                JSON Schema checks structure, but Studio performs additional semantic checks including
                component lookup, required properties, transitions, route integrity and meta-pack compatibility.
                A syntactically valid JSON document is not necessarily a valid Ikasan module.
                """.formatted(metapackVersion);
    }

    public static String modelSchema() {
        return """
                {
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "$id": "https://ikasan.org/studio/model.schema.json",
                  "title": "Ikasan Studio module model",
                  "type": "object",
                  "required": ["applicationPackageName", "name", "version", "flows"],
                  "properties": {
                    "applicationPackageName": { "type": "string", "minLength": 1 },
                    "flowStartupType": { "type": "string" },
                    "h2DbPortNumber": { "type": ["string", "integer"] },
                    "h2WebPortNumber": { "type": ["string", "integer"] },
                    "name": { "type": "string", "minLength": 1 },
                    "port": { "type": ["string", "integer"] },
                    "useEmbeddedH2": { "type": "boolean" },
                    "version": { "type": "string", "minLength": 1 },
                    "flows": { "type": "array", "items": { "$ref": "#/$defs/flow" } }
                  },
                  "additionalProperties": true,
                  "$defs": {
                    "component": {
                      "type": "object",
                      "required": ["componentName", "componentType", "implementingClass"],
                      "properties": {
                        "componentName": { "type": "string", "minLength": 1 },
                        "componentType": { "type": "string", "minLength": 1 },
                        "implementingClass": { "type": "string" },
                        "additionalKey": { "type": "string" }
                      },
                      "additionalProperties": true
                    },
                    "transition": {
                      "type": "object",
                      "required": ["from", "to", "name"],
                      "properties": {
                        "from": { "type": "string", "minLength": 1 },
                        "to": { "type": "string", "minLength": 1 },
                        "name": { "type": "string", "minLength": 1 }
                      },
                      "additionalProperties": false
                    },
                    "flow": {
                      "type": "object",
                      "required": ["name", "consumer", "transitions", "flowElements"],
                      "properties": {
                        "name": { "type": "string", "minLength": 1 },
                        "consumer": { "$ref": "#/$defs/component" },
                        "transitions": { "type": "array", "items": { "$ref": "#/$defs/transition" } },
                        "flowElements": { "type": "array", "items": { "$ref": "#/$defs/component" } },
                        "exceptionResolver": { "$ref": "#/$defs/component" }
                      },
                      "additionalProperties": true
                    }
                  }
                }
                """;
    }

    public static String componentCatalogue(String metapackVersion)
            throws StudioBuildException, JsonProcessingException {
        List<Map<String, Object>> components = new ArrayList<>();
        ComponentLibrary.getIkasanComponents(metapackVersion).entrySet().stream()
                .sorted(Map.Entry.comparingByKey())
                .forEach(entry -> components.add(component(entry.getKey(), entry.getValue())));
        Map<String, Object> catalogue = new LinkedHashMap<>();
        catalogue.put("contractVersion", CONTRACT_VERSION);
        catalogue.put("metapackVersion", metapackVersion);
        String ikasanVersion = ComponentLibrary.getMetaPackManifest(metapackVersion).ikasanVersion();
        catalogue.put("ikasanVersion", ikasanVersion);
        catalogue.put("frameworkReference", frameworkReference(ikasanVersion));
        catalogue.put("components", components);
        return StudioJson.newObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(catalogue) + "\n";
    }

    private static Map<String, Object> frameworkReference(String version) {
        Map<String, Object> reference = new LinkedHashMap<>();
        String repository = "https://github.com/ikasanEIP/ikasan";
        reference.put("repository", repository);
        // Only emit release links verified for bundled targets; custom packs may use other tag conventions.
        if (java.util.Set.of("3.3.9", "4.1.6").contains(version)) {
            String tag = "ikasaneip-" + version;
            reference.put("releaseTag", tag);
            reference.put("releaseSource", repository + "/tree/" + tag);
        }
        reference.put("versionPolicy", "Use the exact resolved Ikasan version and dependency overrides. Never substitute the default branch or another major version. If no releaseSource is supplied, verify the release tag or use matching Maven sources.");
        reference.put("navigation", Map.of(
                "introduction", List.of("README.md", "QuickOverview.md"),
                "interfaces", List.of("ikasaneip/spec"),
                "implementations", List.of("ikasaneip/component"),
                "wiring", List.of("ikasaneip/builder", "ikasaneip/component-factory"),
                "runtime", List.of("ikasaneip/flow", "ikasaneip/module"),
                "failures", List.of("ikasaneip/recovery-manager", "ikasaneip/exclusion", "ikasaneip/hospital", "ikasaneip/replay"),
                "examples", List.of("ikasaneip/sample"),
                "documentation", List.of("ikasaneip/documentation", "UpgradePath.md")));
        reference.put("researchWorkflow", "Follow the catalogue implementingClass to the matching source. Read its interface, implementation, nearby src/test tests and a sample. Check units, defaults, transaction and lifecycle behaviour; cite the release/path. Layout may vary by release. Keep reference source read-only.");
        reference.put("offlineFallback", "Use IntelliJ-attached or cached Maven sources for the resolved dependency version; inspect dependency overrides and class signatures when sources are unavailable. Source links do not grant network permissions. State uncertainty rather than guessing.");
        return reference;
    }

    private static Map<String, Object> component(String key, ComponentMeta meta) {
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("key", key);
        result.put("name", meta.getName());
        result.put("role", meta.getComponentTypeMeta() == null ? null : meta.getComponentTypeMeta().getComponentShortType());
        result.put("componentType", meta.getComponentType());
        result.put("implementingClass", meta.getImplementingClass());
        putText(result, "helpText", meta.getHelpText());
        putText(result, "documentation", meta.getWebHelpURL());
        putText(result, "endpointKey", meta.getEndpointKey());
        result.put("generatesUserImplementedClass", meta.isGeneratesUserImplementedClass());
        result.put("implementationGuidance", meta.isGeneratesUserImplementedClass()
                ? "Inspect the generated user/ implementation. A class may be only a stub; a recipe may supply behaviour. Complete and test it within the requested scope, preserving existing developer logic."
                : "Configure the component using its property help. Check userSuppliedClass properties for required implementation or bean references.");
        result.put("completionChecks", completionChecks(meta));
        boolean ordinaryComponent = !meta.isModule() && !meta.isFlow() && !meta.isEndpoint()
                && !meta.isExceptionResolver();
        result.put("proposalOperations", meta.isExceptionResolver() ? List.of("setExceptionResolution") : meta.isRouter()
                ? List.of("addComponent", "configureRoutes", "setProperty", "renameComponent", "deleteComponent", "replaceComponent", "connect") : meta.isFlow() ? List.of("addFlow", "deleteFlow", "setFlowProperty") : ordinaryComponent
                ? List.of("addComponent", "setProperty", "renameComponent", "deleteComponent", "replaceComponent", "connect") : List.of());
        result.put("proposalSupport", ordinaryComponent ? "Supported in root and named branch routes; routers terminate their parent route. Use route paths for addComponent/connect."
                : meta.isFlow() ? "addFlow creates an empty flow; deleteFlow removes the entire flow and attached test harnesses, retaining developer-owned source files. Use setFlowProperty for metadata-defined flow properties, including flowStartupType. Flow renaming requires Studio."
                : meta.isEndpoint() ? "Associated endpoint; configure its owning component, do not add as a standalone processor."
                : meta.isExceptionResolver() ? "Use setExceptionResolution to add or update a flow-wide exception rule."
                : "Configure in Studio; this role is not a standalone processor.");
        if (meta instanceof org.ikasan.studio.core.metapack.model.ExceptionResolverMeta resolver) {
            result.put("exceptionsCaught", resolver.getExceptionsCaught());
            result.put("exceptionActions", resolver.getActionList().stream().map(action -> {
                Map<String, Object> entry = new LinkedHashMap<>();
                entry.put("name", action.getActionName());
                entry.put("properties", action.getActionProperties().entrySet().stream()
                        .map(p -> property(p.getKey(), p.getValue())).toList());
                entry.put("guidance", switch (action.getActionName()) {
                    case "retry" -> "Bounded retry: delay is milliseconds between retries; legacy property interval is the maximum retry count (not a time interval).";
                    case "retryIndefinitely" -> "Unbounded retry with delay in milliseconds; choose only with an explicit requirement.";
                    case "scheduledCronRetry" -> "Retry on the cron schedule up to maxRetries; verify the expression with the target runtime.";
                    case "excludeEvent" -> "Exclude the failed event; test the exclusion record and subsequent valid processing.";
                    case "ignoreException" -> "Ignore the exception; do not select without an explicit decision about lost/failed work.";
                    default -> "Check the selected version's exception action contract.";
                });
                return entry;
            }).toList());
        }
        if (meta.getAdditionalKey() != null) result.put("additionalKey", meta.getAdditionalKey());
        if (meta.getExpectedInputTypes() != null) result.put("acceptedInputTypes", meta.getExpectedInputTypes());
        if (meta.getProducedOutputType() != null) result.put("producedOutputType", meta.getProducedOutputType());
        if (meta.getConversionRecipes() != null && !meta.getConversionRecipes().isEmpty()) {
            result.put("conversionRecipes", meta.getConversionRecipes());
            result.put("recipeConfigurations", meta.getConversionRecipes().stream()
                    .map(recipe -> Map.of("conversionRecipeId", recipe.getId(),
                            "fromType", recipe.getSourceType(), "toType", recipe.getTargetType())).toList());
        }
        List<Map<String, Object>> properties = new ArrayList<>();
        meta.getAllowableProperties().forEach((name, property) -> properties.add(property(name, property)));
        result.put("properties", properties);
        return result;
    }

    private static List<String> completionChecks(ComponentMeta meta) {
        List<String> checks = new ArrayList<>();
        if (meta.isModule() || meta.isFlow() || meta.isEndpoint()) {
            checks.add("Verify the configured components and transport relationships; this container or endpoint is not an independent processor implementation.");
            if (meta.isModule() || meta.isFlow())
                checks.add("Verify normal Studio Run module startup and effective per-flow startup controls, not only a custom test launcher. Keep normal flows AUTOMATIC; report unavailable services as blockers without disabling flows. Use MANUAL or DISABLED only when explicitly requested by the developer. Check observed state and replay after sample delivery.");
            return checks;
        }
        checks.add("Trace a representative input through the component and test the expected output or side effect, including a relevant failure case.");
        if (meta.isGeneratesUserImplementedClass()) {
            checks.add("Locate the generated user/ class and inspect its method bodies. Complete throwing, empty or no-op scaffolds within the requested scope; preserve existing developer logic.");
        }
        String role = meta.getComponentTypeMeta() == null ? "" : meta.getComponentTypeMeta().getComponentShortType();
        checks.add(switch (role) {
            case "Consumer" -> "Verify emitted payload type, listener/event-factory wiring, required provider beans and start/stop lifecycle. A sample source must emit usable sample events. Verify owned workers terminate and stop/start does not duplicate delivery. ESB flows must remain running after sample delivery and accept later input without restart. Test idle readiness and a second batch. Finite sources are only for explicitly requested batch examples or bounded tests; null terminates an Event Generating Consumer, it is not an idle signal.";
            case "Producer" -> "Verify the actual destination or observable output, payload compatibility and error handling. An empty invoke method is not a working producer. For file output, test interrupted publication and retry; idempotent filenames alone do not prevent partial files.";
            case "Converter" -> "Implement the declared source-to-target transformation or verify the selected recipe. Test real output values and unsupported input; do not leave UnsupportedOperationException.";
            case "Splitter" -> "Return meaningful records in the intended order. Test multiple records and empty/invalid input; returning an empty list for every input is not an implementation.";
            case "Filter" -> "Implement an explicit acceptance rule and test accepted and rejected inputs. An unconditional pass-through does not demonstrate filtering.";
            case "Translator" -> "Perform and test the intended in-place mutation of a mutable payload. Use a Converter for replacement values.";
            case "Broker" -> "Implement and test the requested lookup, enrichment or request/response behavior; returning unchanged input is not evidence of enrichment.";
            default -> "Check the selected version's interfaces and component help for its behavior and configuration contract.";
        });
        checks.add("Verify required beans and external resources independently of compilation. Report runtime delivery as unverified until exercised.");
        return List.copyOf(checks);
    }

    private static void putText(Map<String, Object> target, String key, String value) {
        if (value != null && !value.isBlank()) target.put(key, value);
    }

    private static Map<String, Object> property(String name, ComponentPropertyMeta meta) {
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("name", name);
        result.put("required", meta.isMandatory());
        putText(result, "displayLabel", meta.getDisplayLabel());
        putText(result, "helpText", meta.getHelpText());
        result.put("userSuppliedClass", meta.isUserSuppliedClass());
        if (meta.isUserSuppliedClass()) result.put("beanRequirement", meta.isNoStubRequired()
                ? "Locate the existing configured bean/provider, verify its required type and injection name/qualifier, and check dependency and scan configuration. No stub is generated or appropriate for this external reference."
                : "Locate the implementation and Spring registration, verify the required interface and injection name/qualifier, and check component scanning. Do not assume a model reference generated a class. If missing, implement/register it in user/ within the requested scope after checking the selected version's API; preserve existing beans.");
        result.put("protectFromOverwrite", meta.isProtectFromOverwrite());
        result.put("noStubRequired", meta.isNoStubRequired());
        result.put("affectsUserImplementedClass", meta.isAffectsUserImplementedClass());
        result.put("type", meta.getPropertyDataType() == null ? "java.lang.String" : meta.getPropertyDataType().getName());
        if (meta.getUsageDataType() != null && !meta.getUsageDataType().isBlank()) result.put("usageType", meta.getUsageDataType());
        if (ComponentPropertyMeta.isSubstitutionValue(meta.getDefaultValue())) {
            result.put("defaultExpression", meta.getDefaultValue());
            result.put("defaultGuidance", "Studio resolves this expression when creating a component. Omit the property or supply a concrete value; never copy the expression into a proposal as a literal.");
        } else if (meta.getDefaultValue() != null) result.put("default", meta.getDefaultValue());
        boolean structural = java.util.Set.of("componentName", "name", "version", "testHarnessOwner", "routeNames").contains(name)
                || meta.isIgnoreProperty();
        boolean implementationChange = meta.isAffectsUserImplementedClass()
                && !(meta.isUserSuppliedClass() && meta.isProtectFromOverwrite());
        result.put("setPropertySupported", !structural && !implementationChange);
        if (structural || implementationChange) result.put("editGuidance", structural
                ? "Use a supported structural operation rather than setProperty."
                : "Choose this value in addComponent/replaceComponent properties. Existing implementation changes require Studio; preserve developer-owned code. A userImplementedClassName containing an unresolved __fieldName: expression can be repaired with setProperty and a concrete Java class name.");
        if (meta.getChoices() != null && !meta.getChoices().isEmpty()) result.put("choices", meta.getChoices());
        if (meta.isHiddenProperty()) result.put("hidden", true);
        if (meta.isChoicesEditable()) result.put("choicesEditable", true);
        if (meta.getValidation() != null && !meta.getValidation().isBlank()) result.put("validation", meta.getValidation());
        if (meta.getMandatoryIfTrue() != null) result.put("mandatoryIfTrue", meta.getMandatoryIfTrue());
        if (meta.getMandatoryUnlessAnyOf() != null) result.put("mandatoryUnlessAnyOf", meta.getMandatoryUnlessAnyOf());
        return result;
    }
}
