package ${studioPackageTag};

/**
* Studio-only REST endpoint used by IntelliJ debugging to inject a synthetic test event directly into a
* named flow's Consumer entry point, bypassing the real broker. Only active under the "studio-debug" Spring
* profile, which Ikasan Studio's "Debug module" launch activates automatically.
* Nested under /rest/** rather than a standalone /studio/** path: Ikasan's own default security config
* (WebSecurityConfig, pulled in unconditionally via IkasanBaseAutoConfiguration) already both permitAll()s
* and CSRF-exempts /rest/**, whereas an unmatched path is only permitAll()'d, not CSRF-exempt - a POST here
* would otherwise 403 from the CSRF filter itself before authorization is even considered.
* This file is auto-generated by Ikasan Studio, do no edit.
*/
@org.springframework.context.annotation.Profile("studio-debug")
@org.springframework.web.bind.annotation.RestController
@org.springframework.web.bind.annotation.RequestMapping("/rest/studio/inject")
public class ${className} {

@javax.annotation.Resource
org.ikasan.spec.module.Module myModule;

// Optional rather than a hard dependency: a module whose flows hold no transactional resources injects
// perfectly well without one, and a generated file must never be the reason the module fails to start.
// Qualified by name because Spring Boot can publish more than one PlatformTransactionManager - "transactionManager"
// is the JTA one Ikasan's own IkasanTransactionConfiguration declares, which is the one the endpoints enlist into.
@org.springframework.beans.factory.annotation.Autowired(required = false)
@org.springframework.beans.factory.annotation.Qualifier("transactionManager")
org.springframework.transaction.PlatformTransactionManager studioTransactionManager;

@org.springframework.web.bind.annotation.GetMapping("/flows")
public java.util.List<String> listFlows() {
    java.util.List<String> names = new java.util.ArrayList<>();
    for (Object flow : myModule.getFlows()) {
        names.add(((org.ikasan.spec.flow.Flow) flow).getName());
    }
    return names;
}

@org.springframework.web.bind.annotation.PostMapping("/{flowName}")
public org.springframework.http.ResponseEntity<?> inject(
        // Explicit "flowName" name, not just @PathVariable String flowName: Spring Framework 6.1 dropped the
        // debug-symbol-based (LocalVariableTableParameterNameDiscoverer) fallback that used to make an
        // unnamed @PathVariable work as long as the class still carried debug info (IntelliJ's default Debug
        // compile does) - only the -parameters compiler flag or an explicit name works now, and this project's
        // build doesn't set -parameters, so leave it explicit rather than depend on that.
        @org.springframework.web.bind.annotation.PathVariable("flowName") String flowName,
        @org.springframework.web.bind.annotation.RequestBody InjectRequest request) {
    Object rawFlow = myModule.getFlow(flowName);
    if (rawFlow == null) {
        return org.springframework.http.ResponseEntity.status(404).body("No such flow: " + flowName);
    }
    if (request.getPayload() == null) {
        return org.springframework.http.ResponseEntity.badRequest().body("payload is required");
    }
    org.ikasan.spec.flow.Flow flow = (org.ikasan.spec.flow.Flow) rawFlow;
    try {
        org.ikasan.spec.flow.FlowElement consumerElement = flow.getFlowConfiguration().getConsumerFlowElement();
        org.ikasan.spec.component.endpoint.Consumer consumer = (org.ikasan.spec.component.endpoint.Consumer) consumerElement.getFlowComponent();
        org.ikasan.spec.event.EventFactory eventFactory = (org.ikasan.spec.event.EventFactory) consumer.getEventFactory();
        String identifier = request.getIdentifier() != null ? request.getIdentifier() : java.util.UUID.randomUUID().toString();
        // If the user picked a payload class in the dialog (or Send Test Message built one itself, e.g. the
        // file picker for a file-list Consumer - see SendTestMessageAction), the payload text is JSON to
        // deserialize rather than the raw string. constructFromCanonical accepts both a plain class name (a
        // user's own POJO) and a canonical generic type such as "java.util.List<java.io.File>" (Jackson has
        // built-in java.io.File support, so a JSON array of path strings becomes a real List<File> with no
        // custom class needed) - resolved against flow's classloader for the same reason newSyntheticJmsMessage
        // below needs to (see its comment). setVisibility(FIELD, ANY) makes Jackson bind directly to fields
        // regardless of access modifier or whether a getter/setter exists - "Generate Sample JSON" in the
        // dialog offers every field of the chosen class as a JSON key, including plain package-private ones
        // with no accessors, so deserialization needs to accept exactly those same fields or it rejects its own
        // generated payload (Jackson's default visibility only auto-detects public fields/accessors).
        Object rawPayload = (request.getPayloadClassName() != null && !request.getPayloadClassName().isBlank())
                ? new com.fasterxml.jackson.databind.ObjectMapper()
                        .setVisibility(com.fasterxml.jackson.annotation.PropertyAccessor.FIELD, com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility.ANY)
                        .readValue(request.getPayload(),
                        com.fasterxml.jackson.databind.type.TypeFactory.defaultInstance()
                                .withClassLoader(flow.getClass().getClassLoader())
                                .constructFromCanonical(request.getPayloadClassName()))
                : request.getPayload();
        // JMS-backed consumers are also a Converter<Message,Object> that unconditionally runs before the flow
        // proper, expecting a real jakarta.jms.Message rather than the raw payload - synthesize a minimal one.
        Object payload = (consumer instanceof jakarta.jms.MessageListener)
                ? newSyntheticJmsMessage(rawPayload, flow.getClass().getClassLoader())
                : rawPayload;
        Object event = eventFactory.newEvent(identifier, payload);
        invokeInTransaction(flow, event);
        java.util.Map<String, String> responseBody = new java.util.HashMap<>();
        responseBody.put("status", "invoked");
        responseBody.put("identifier", identifier);
        return org.springframework.http.ResponseEntity.ok(responseBody);
    } catch (Exception e) {
        return org.springframework.http.ResponseEntity.status(500).body("Failed to inject event: " + e.getMessage());
    }
}

/**
* Drives the flow inside a real JTA transaction, the way a live Consumer's own container does.
* Transactional endpoints (SFTP/FTP/JMS producers) enlist an XAResource via
* TransactionManager.getTransaction().enlistResource(..) and fail outright with a NullPointerException when no
* transaction is bound to the calling thread - which is exactly the case here, since this REST endpoint invokes
* the flow straight from its Tomcat request thread rather than from a transactional consumer. The commit is also
* where those endpoints do the real work (an FTP/SFTP producer defers its .tmp-to-final rename to commit time),
* so the transaction has to wrap the invoke rather than merely precede it.
*/
private void invokeInTransaction(org.ikasan.spec.flow.Flow flow, Object event) {
    if (studioTransactionManager == null) {
        ((org.ikasan.spec.event.EventListener) flow).invoke(event);
        return;
    }
    org.springframework.transaction.support.DefaultTransactionDefinition transactionDefinition =
            new org.springframework.transaction.support.DefaultTransactionDefinition(
                    org.springframework.transaction.TransactionDefinition.PROPAGATION_REQUIRED);
    transactionDefinition.setName("studio-inject");
    org.springframework.transaction.TransactionStatus transaction =
            studioTransactionManager.getTransaction(transactionDefinition);
    try {
        ((org.ikasan.spec.event.EventListener) flow).invoke(event);
    } catch (RuntimeException | Error invocationFailure) {
        rollbackQuietly(transaction);
        throw invocationFailure;
    }
    // Deliberately outside the try: a commit failure has already unwound the transaction itself, so it must not
    // be handed to rollbackQuietly as well - it just propagates to inject()'s own catch and becomes the 500.
    studioTransactionManager.commit(transaction);
}

/**
* Rolls back without letting a rollback failure mask the original one - this is only ever called while already
* unwinding from the failure that actually matters to the developer.
*/
private void rollbackQuietly(org.springframework.transaction.TransactionStatus transaction) {
    try {
        if (!transaction.isCompleted()) {
            studioTransactionManager.rollback(transaction);
        }
    } catch (RuntimeException | Error rollbackFailure) {
        // Intentionally ignored - see javadoc.
    }
}

// Implements both TextMessage and ObjectMessage on the one proxy so it works regardless of which one the
// consumer/downstream converter actually expects: getObject() hands back the real payload value (a String,
// or the deserialized payload-class instance), while getText() falls back to its String.valueOf() so a
// TextMessage-only reader still gets something sane. JmsMessageConverter.extractContent() checks TextMessage
// first, so with autoContentConversion on this is always read as text; leave autoContentConversion off (so
// the raw message reaches a downstream component like JMS Object Message To Object Converter untouched) to
// exercise the ObjectMessage path - the only way a payload-class instance survives intact rather than being
// stringified. Everything else on either interface can safely return a zero/null default via a dynamic
// proxy, avoiding a dependency on any specific JMS provider (e.g. ActiveMQ) not guaranteed to be on the
// classpath for every JMS consumer.
// The defining classloader matters and must be passed in from the caller: under Spring Boot's embedded Tomcat,
// this controller class itself can be loaded by a TomcatEmbeddedWebappClassLoader that holds its OWN separate
// copy of jakarta.jms.* (so neither Thread.currentThread().getContextClassLoader() nor
// SomeJmsInterface.class.getClassLoader(), both resolved from THIS class, escape it) - a proxy built against
// that loader implements a same-named-but-distinct ObjectMessage/TextMessage Class object, so a real checkcast
// against it (e.g. ObjectMessageToObjectConverter's generic bridge method) throws ClassCastException even
// though the interface names match. flow's classloader is guaranteed correct instead: Spring can only have
// wired the flow together with its Consumer/Converter components (loaded from ikasan-* jars) if they're all
// mutually visible on one delegation chain, so flow.getClass().getClassLoader() reaches the same jakarta.jms
// those Ikasan classes see.
private static Object newSyntheticJmsMessage(Object value, ClassLoader ikasanClassLoader) throws ClassNotFoundException {
    // The interface Class objects must themselves be resolved via ikasanClassLoader too, not referenced as
    // jakarta.jms.TextMessage.class literals (which the compiler would resolve via THIS class's own loader) -
    // Proxy.newProxyInstance requires every interface to be the exact same Class object as loader would
    // resolve, or it throws IllegalArgumentException("interface not visible from class loader").
    Class<?> textMessageClass = Class.forName("jakarta.jms.TextMessage", false, ikasanClassLoader);
    Class<?> objectMessageClass = Class.forName("jakarta.jms.ObjectMessage", false, ikasanClassLoader);
    return java.lang.reflect.Proxy.newProxyInstance(
            ikasanClassLoader,
            new Class<?>[] { textMessageClass, objectMessageClass },
            (proxy, method, args) -> {
                if ("getText".equals(method.getName())) {
                    return String.valueOf(value);
                }
                if ("getObject".equals(method.getName())) {
                    return value;
                }
                if ("toString".equals(method.getName()) && (args == null || args.length == 0)) {
                    return "SyntheticJmsMessage[" + value + "]";
                }
                Class<?> returnType = method.getReturnType();
                if (returnType == java.util.Enumeration.class) {
                    // getPropertyNames() - ActiveMQMessageTransformation.copyProperties (seen crashing twice
                    // already on this synthetic message, for different reasons) enumerates this without a
                    // null check first; an empty enumeration is both type-safe and semantically correct,
                    // since this synthetic message has no custom properties.
                    return java.util.Collections.emptyEnumeration();
                }
                if (returnType == void.class) {
                    // void.class.isPrimitive() is true, so this must be checked before the primitive branch
                    // below - e.g. setStringProperty(...)/clearProperties() return nothing, and
                    // Array.newInstance(void.class, 1) itself throws IllegalArgumentException.
                    return null;
                }
                if (returnType == boolean.class) {
                    return false;
                }
                if (returnType.isPrimitive()) {
                    // A 1-element array of returnType is JVM-zero-initialised; reading element 0 back
                    // autoboxes to the EXACT wrapper class matching returnType (Long for long, Short for
                    // short, etc.) - Proxy.invoke requires that exact match or throws ClassCastException, as
                    // a bare "return 0" (always boxed Integer) did for every long-returning javax/jakarta.jms
                    // Message method (getJMSExpiration/getJMSTimestamp/getJMSDeliveryTime), since an Integer
                    // cannot be unboxed to long.
                    return java.lang.reflect.Array.get(java.lang.reflect.Array.newInstance(returnType, 1), 0);
                }
                return null;
            });
}

public static class InjectRequest {
    private String identifier;
    private String payload;
    // Fully-qualified name of a project class to deserialize payload (as JSON) into before injection - see
    // SendTestMessagePayloadDialog. Null means the default plain-text/string payload.
    private String payloadClassName;
    public String getIdentifier() { return identifier; }
    public void setIdentifier(String identifier) { this.identifier = identifier; }
    public String getPayload() { return payload; }
    public void setPayload(String payload) { this.payload = payload; }
    public String getPayloadClassName() { return payloadClassName; }
    public void setPayloadClassName(String payloadClassName) { this.payloadClassName = payloadClassName; }
}
}
