package org.ikasan.studio.boot.flow.flow1;

import org.ikasan.builder.BuilderFactory;
import org.ikasan.spec.component.endpoint.Consumer;
import org.ikasan.spec.component.endpoint.Producer;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;

import javax.annotation.Resource;

/**
 * The component factory defines the details of the components and their configuration.
 * <p>
 * This file is auto-generated by Ikasan Studio, do no edit.
 */
@Configuration
public class ComponentFactoryFlow1 {
    @Value("${module.name}")
    private String moduleName;

    @Resource
    BuilderFactory builderFactory;


    public Consumer getEgc() {
        return builderFactory.getComponentBuilder().eventGeneratingConsumer()
                .build();
    }

    public Producer getLp() {
        return builderFactory.getComponentBuilder().logProducer()
                .build();
    }
}