package ${studioPackageTag};

/**
* This class is used to support debug components in flows.
* This file is auto-generated by Ikasan Studio, do no edit.
*/
public abstract class ${className} implements org.ikasan.spec.component.filter.Filter<Object> {
    @Override
    public final Object filter(Object payload) throws org.ikasan.spec.component.filter.FilterException {
        debug(org.ikasan.studio.component.utils.DeepCopyUtil.deepCopy(payload));
        return payload;
    }

    /**
     * Expose the payload for debugging purposes
     * @param payload the incoming payload
     */
    public abstract void debug(Object payload);
}