package ${studioPackageTag};

/**
* This class is used to support debug components in flows.
* This file is auto-generated by Ikasan Studio, do no edit.
*/
public abstract class ${className} implements org.ikasan.spec.component.filter.Filter<Object> {
    @Override
    public final Object filter(Object message) throws org.ikasan.spec.component.filter.FilterException {
        debug(org.ikasan.studio.component.utils.DeepCopyUtil.deepCopy(message));
        return message;
    }

    /**
     * Expose the payload for debugging purposes
     * @param message the message payload
     */
    public abstract void debug(Object message);
}