package ${studioPackageTag};

/**
* Attempt to deep copy a payload either by serialisation or reflection, so debugging a payload can never
* mutate what the flow is actually processing.
* This file is auto-generated by Ikasan Studio, do no edit.
*/
public class ${className} {
    /**
     * Attempt to deep copy the supplied Object either by serialisation or reflection
     * @param original object to be duplicated
     * @return either a copy of the object or a reference to the object if copying was not possible
     * @param <T> type of object to be duplicated
     */
    @SuppressWarnings("unchecked")
    public static <T> T deepCopy(T original) {
        if (original != null) {
            if (original instanceof java.io.Serializable) {
                try {
                    java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
                    java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(baos);
                    oos.writeObject(original);

                    java.io.ByteArrayInputStream bais = new java.io.ByteArrayInputStream(baos.toByteArray());
                    java.io.ObjectInputStream ois = new java.io.ObjectInputStream(bais);

                    return (T) ois.readObject();
                } catch (java.io.IOException | ClassNotFoundException e) {
                    return original;
                }
            } else {
                T copy;
                try {
                    copy = (T) original.getClass().getDeclaredConstructor().newInstance();
                } catch (NoSuchMethodException | java.lang.reflect.InvocationTargetException | IllegalAccessException | InstantiationException e) {
                    return original;
                }
                try {
                    for (java.lang.reflect.Field field : original.getClass().getDeclaredFields()) {
                        field.setAccessible(true);
                        field.set(copy, field.get(original));
                    }
                } catch (IllegalAccessException e) {
                    return original;
                }
                return copy;
            }
        }
        return original;
    }
}