package ${studioPackageTag};

/**
* Studio-only REST endpoint used by IntelliJ debugging to inject a synthetic test event directly into a
* named flow's Consumer entry point, bypassing the real broker. Only active under the "studio-debug" Spring
* profile, which Ikasan Studio's "Debug module" launch activates automatically.
* This file is auto-generated by Ikasan Studio, do no edit.
*/
@org.springframework.context.annotation.Profile("studio-debug")
@org.springframework.web.bind.annotation.RestController
@org.springframework.web.bind.annotation.RequestMapping("/studio/inject")
public class ${className} {

@javax.annotation.Resource
org.ikasan.spec.module.Module myModule;

@org.springframework.web.bind.annotation.GetMapping("/flows")
public java.util.List<String> listFlows() {
    java.util.List<String> names = new java.util.ArrayList<>();
    for (Object flow : myModule.getFlows()) {
        names.add(((org.ikasan.spec.flow.Flow) flow).getName());
    }
    return names;
}

@org.springframework.web.bind.annotation.PostMapping("/{flowName}")
public org.springframework.http.ResponseEntity<?> inject(
        @org.springframework.web.bind.annotation.PathVariable String flowName,
        @org.springframework.web.bind.annotation.RequestBody InjectRequest request) {
    Object rawFlow = myModule.getFlow(flowName);
    if (rawFlow == null) {
        return org.springframework.http.ResponseEntity.status(404).body("No such flow: " + flowName);
    }
    if (request.getPayload() == null) {
        return org.springframework.http.ResponseEntity.badRequest().body("payload is required");
    }
    org.ikasan.spec.flow.Flow flow = (org.ikasan.spec.flow.Flow) rawFlow;
    try {
        org.ikasan.spec.flow.FlowElement consumerElement = flow.getFlowConfiguration().getConsumerFlowElement();
        org.ikasan.spec.component.endpoint.Consumer consumer = (org.ikasan.spec.component.endpoint.Consumer) consumerElement.getFlowComponent();
        org.ikasan.spec.event.EventFactory eventFactory = (org.ikasan.spec.event.EventFactory) consumer.getEventFactory();
        String identifier = request.getIdentifier() != null ? request.getIdentifier() : java.util.UUID.randomUUID().toString();
        // JMS-backed consumers are also a Converter<Message,Object> that unconditionally runs before the flow
        // proper, expecting a real javax.jms.Message rather than the raw payload - synthesize a minimal one.
        Object payload = (consumer instanceof javax.jms.MessageListener)
                ? newSyntheticTextMessage(request.getPayload())
                : request.getPayload();
        Object event = eventFactory.newEvent(identifier, payload);
        ((org.ikasan.spec.event.EventListener) flow).invoke(event);
        java.util.Map<String, String> responseBody = new java.util.HashMap<>();
        responseBody.put("status", "invoked");
        responseBody.put("identifier", identifier);
        return org.springframework.http.ResponseEntity.ok(responseBody);
    } catch (Exception e) {
        return org.springframework.http.ResponseEntity.status(500).body("Failed to inject event: " + e.getMessage());
    }
}

// Only getText() is load-bearing for JmsMessageConverter.extractContent's TextMessage branch - everything
// else on the interface can safely return a zero/null default via a dynamic proxy, avoiding a dependency on
// any specific JMS provider (e.g. ActiveMQ) not guaranteed to be on the classpath for every JMS consumer.
private static Object newSyntheticTextMessage(String text) {
    return java.lang.reflect.Proxy.newProxyInstance(
            Thread.currentThread().getContextClassLoader(),
            new Class<?>[] { javax.jms.TextMessage.class },
            (proxy, method, args) -> {
                if ("getText".equals(method.getName())) {
                    return text;
                }
                Class<?> returnType = method.getReturnType();
                if (returnType == boolean.class) {
                    return false;
                }
                if (returnType.isPrimitive()) {
                    return 0;
                }
                return null;
            });
}

public static class InjectRequest {
    private String identifier;
    private String payload;
    public String getIdentifier() { return identifier; }
    public void setIdentifier(String identifier) { this.identifier = identifier; }
    public String getPayload() { return payload; }
    public void setPayload(String payload) { this.payload = payload; }
}
}
