package org.ikasan.studio.boot;

/**
* This is the Spring boot start class.
* This file is auto-generated by Ikasan Studio, do no edit.
*/
@org.springframework.boot.autoconfigure.SpringBootApplication
@org.springframework.context.annotation.ComponentScan({"org.ikasan.studio.boot", "co.uk.test"})
public class Application {
public static void main(String[] args) {
org.springframework.boot.SpringApplication.run(Application.class, args);
}}