package org.ikasan;

/**
* The component factory defines the details of the components and their configuration.
*
* This file is auto-generated by Ikasan Studio, do no edit.
*/
@org.springframework.context.annotation.Configuration
public class ComponentFactoryMyFlow1
{
@org.springframework.beans.factory.annotation.Value("${module.name}")
private String moduleName;

@javax.annotation.Resource
org.ikasan.builder.BuilderFactory builderFactory;

@org.springframework.beans.factory.annotation.Value("${myflow1.testftpproducer.ftp.producer.max-retry-attempts}")
java.lang.Integer ftpProducerMaxretryattempts;
@org.springframework.beans.factory.annotation.Value("${myflow1.testftpproducer.ftp.producer.outputDirectory}")
java.lang.String ftpProducerOutputDirectory;
@org.springframework.beans.factory.annotation.Value("${myflow1.testftpproducer.ftp.producer.ftps-protocol}")
java.lang.String ftpProducerFtpsprotocol;
@org.springframework.beans.factory.annotation.Value("${myflow1.testftpproducer.ftp.producer.password}")
java.lang.String ftpProducerPassword;
@org.springframework.beans.factory.annotation.Value("${myflow1.testftpproducer.ftp.producer.remote-port}")
java.lang.Integer ftpProducerRemoteport;
@org.springframework.beans.factory.annotation.Value("${myflow1.testftpproducer.ftp.producer.ftps-port}")
java.lang.Integer ftpProducerFtpsport;
@org.springframework.beans.factory.annotation.Value("${myflow1.testftpproducer.ftp.producer.system-key}")
java.lang.String ftpProducerSystemkey;
@org.springframework.beans.factory.annotation.Value("${myflow1.testftpproducer.ftp.producer.remote-host}")
java.lang.String ftpProducerRemotehost;
@org.springframework.beans.factory.annotation.Value("${myflow1.testftpproducer.ftp.producer.username}")
java.lang.String ftpProducerUsername;
@org.springframework.beans.factory.annotation.Value("${myflow1.testftpproducer.ftp.producer.clientID}")
java.lang.String ftpProducerClientID;
@javax.annotation.Resource
org.ikasan.endpoint.ftp.producer.FtpProducerConfiguration myConfigurationClass;
@javax.annotation.Resource
org.ikasan.spec.management.ManagedResourceRecoveryManager myManagedResourceRecoveryManagerClass;
@javax.annotation.Resource
org.springframework.transaction.jta.JtaTransactionManager myTransactionManagerClass;

public org.ikasan.spec.component.endpoint.Producer getTestFtpProducer() {
return builderFactory.getComponentBuilder().ftpProducer()
.setTempFileName("myTempFileName")
.setMaxRetryAttempts(ftpProducerMaxretryattempts)
.setConfiguration(myConfigurationClass)
.setOutputDirectory(ftpProducerOutputDirectory)
.setChecksumDelivered(true)
.setManagedResourceRecoveryManager(myManagedResourceRecoveryManagerClass)
.setFtpsProtocol(ftpProducerFtpsprotocol)
.setFtpsKeyStoreFilePassword("myFtpsKeyStoreFilePassword")
.setSocketTimeout(22)
.setCleanupJournalOnComplete(true)
.setPassword(ftpProducerPassword)
.setCriticalOnStartup(true)
.setCreateParentDirectory(true)
.setOverwrite(true)
.setFtpsKeyStoreFilePath("/test/ftps/keystore")
.setFtpsIsImplicit(true)
.setRemotePort(ftpProducerRemoteport)
.setUnzip(true)
.setFtpsPort(ftpProducerFtpsport)
.setSystemKey(ftpProducerSystemkey)
.setRenameExtension("newExtension")
.setFTPS(true)
.setActive(true)
.setRemoteHost(ftpProducerRemotehost)
.setConfiguredResourceId("myUniqueConfiguredResourceIdName")
.setUsername(ftpProducerUsername)
.setTransactionManager(myTransactionManagerClass)
.setDataTimeout(300001)
.setClientID(ftpProducerClientID)
.build();
}}