package org.ikasan;

/**
* The component factory defines the details of the components and their configuration.
*
* This file is auto-generated by Ikasan Studio, do no edit.
*/
@org.springframework.context.annotation.Configuration
public class ComponentFactoryMyFlow1
{
@org.springframework.beans.factory.annotation.Value("${module.name}")
private String moduleName;

@javax.annotation.Resource
org.ikasan.builder.BuilderFactory builderFactory;

@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.producer.remote-port}")
java.lang.Integer myFlow1SftpProducerRemoteport;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.producer.clientID}")
java.lang.String myFlow1SftpProducerClientID;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.producer.max-retry-attempts}")
java.lang.Integer myFlow1SftpProducerMaxretryattempts;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.producer.username}")
java.lang.String myFlow1SftpProducerUsername;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.producer.outputDirectory}")
java.lang.String myFlow1SftpProducerOutputDirectory;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.producer.password}")
java.lang.String myFlow1SftpProducerPassword;
@org.springframework.beans.factory.annotation.Value("${myflow1.sftp.producer.remote-host}")
java.lang.String myFlow1SftpProducerRemotehost;
@javax.annotation.Resource
org.ikasan.endpoint.ftp.producer.FtpProducerConfiguration myConfigurationClass;
@javax.annotation.Resource
org.ikasan.spec.management.ManagedResourceRecoveryManager myManagedResourceRecoveryManagerClass;

public org.ikasan.spec.component.endpoint.Producer getTestSftpProducer() {
return builderFactory.getComponentBuilder().sftpProducer()
.setRemotePort(myFlow1SftpProducerRemoteport)
.setClientID(myFlow1SftpProducerClientID)
.setChecksumDelivered(true)
.setUnzip(true)
.setCleanupJournalOnComplete(true)
.setMaxRetryAttempts(myFlow1SftpProducerMaxretryattempts)
.setUsername(myFlow1SftpProducerUsername)
.setConfiguration(myConfigurationClass)
.setCreateParentDirectory(true)
.setOutputDirectory(myFlow1SftpProducerOutputDirectory)
.setManagedResourceRecoveryManager(myManagedResourceRecoveryManagerClass)
.setPassword(myFlow1SftpProducerPassword)
.setRemoteHost(myFlow1SftpProducerRemotehost)
.setPrivateKeyFilename("myPrivateKeyFilename")
.setConnectionTimeout(300001)
.setTempFileName("myTempFileName")
.setRenameExtension("newExtension")
.setPreferredKeyExchangeAlgorithm("myPreferredKeyExchangeAlgorithm")
.setCriticalOnStartup(true)
.setKnownHostsFilename("myKnownHostsFilename")
.setConfiguredResourceId("myUniqueConfiguredResourceIdName")
.setCleanUpChunks(true)
.build();
}}