package org.ikasan;

/**
* The component factory defines the details of the components and their configuration.
*
* This file is auto-generated by Ikasan Studio, do no edit.
*/
@org.springframework.context.annotation.Configuration
public class ComponentFactoryMyFlow1
{
@org.springframework.beans.factory.annotation.Value("${module.name}")
private String moduleName;

@javax.annotation.Resource
org.ikasan.builder.BuilderFactory builderFactory;

@org.springframework.beans.factory.annotation.Value("${myflow1.ftp.consumer.cron-expression}")
java.lang.String myFlow1FtpConsumerCronexpression;
@javax.annotation.Resource
org.ikasan.spec.event.ManagedEventIdentifierService myManagedEventIdentifierServiceClass;
@javax.annotation.Resource
org.ikasan.component.endpoint.quartz.consumer.MessageProvider myMessageProviderClass;
@javax.annotation.Resource
org.ikasan.component.endpoint.filesystem.messageprovider.FileConsumerConfiguration myConfigurationClass;
@javax.annotation.Resource
org.ikasan.spec.management.ManagedResourceRecoveryManager myManagedResourceRecoveryManagerClass;
@javax.annotation.Resource
org.ikasan.spec.event.EventFactory myEventFactory;

public org.ikasan.spec.component.endpoint.Consumer getTestScheduledConsumer() {
return builderFactory.getComponentBuilder().scheduledConsumer()
.setCronExpression(myFlow1FtpConsumerCronexpression)
.setIgnoreMisfire(true)
.setManagedEventIdentifierService(myManagedEventIdentifierServiceClass)
.setMessageProvider(myMessageProviderClass)
.setMaxEagerCallbacks(1)
.setTimezone("UTC")
.setScheduledJobGroupName("myScheduledJobGroupName")
.setConfiguration(myConfigurationClass)
.setManagedResourceRecoveryManager(myManagedResourceRecoveryManagerClass)
.setEventFactory(myEventFactory)
.setEager(true)
.setScheduledJobName("myScheduledJobName")
.setCriticalOnStartup(true)
.setConfiguredResourceId("myUniqueConfiguredResourceIdName")
.build();
}}