/**
* Component factory.
*
* This file is auto-generated by Ikasan Studio, do no edit..
*
* @author Ikasan Development Team
*/
@org.springframework.context.annotation.Configuration
public class ComponentFactory
{
@org.springframework.beans.factory.annotation.Value("${module.name}")
private String moduleName;

@javax.annotation.Resource
org.ikasan.builder.BuilderFactory builderFactory;

@org.springframework.beans.factory.annotation.Value("${myflow1.testftpconsumer.ftp.consumer.cronExpression}")
java.lang.String  ftpConsumerCronexpression;
@org.springframework.beans.factory.annotation.Value("${myflow1.testftpconsumer.ftp.consumer.FilenamePattern}")
java.lang.String  ftpConsumerFilenamepattern;

public org.ikasan.spec.component.endpoint.Consumer getftpConsumer() {
return builderFactory.getComponentBuilder().ftpConsumer()
.setActive(true)
.setCronExpression(ftpConsumerCronexpression)
.setFilenamePattern(ftpConsumerFilenamepattern)
.build();
}
}