package org.ikasan;

/**
* The component factory defines the details of the components and their configuration.
*
* This file is auto-generated by Ikasan Studio, do no edit.
*/
@org.springframework.context.annotation.Configuration
public class ComponentFactoryMyFlow1
{
@org.springframework.beans.factory.annotation.Value("${module.name}")
private String moduleName;

@javax.annotation.Resource
org.ikasan.builder.BuilderFactory builderFactory;

@javax.annotation.Resource
org.myApp.myflow1.MyFilter testFilterComponent;
@javax.annotation.Resource
org.myApp.myflow1.MyConfigurationClass myConfigurationClass;

public org.ikasan.spec.component.filter.Filter getTestFilterComponent() {
testFilterComponent.setConfiguration(myConfigurationClass);
testFilterComponent.setConfiguredResourceId("MyConfiguredResourceId");
return testFilterComponent;
}}