/**
* This is the Spring book start class.
* This file is auto-generated by Ikasan Studio, do no edit..
*/
@org.springframework.context.annotation.Configuration("ModuleFactory")
@org.springframework.context.annotation.ImportResource({
"classpath:h2-datasource-conf.xml",
"classpath:ikasan-transaction-pointcut-ikasanMessageListener.xml"
})
public class ModuleConfig {
@javax.annotation.Resource
org.ikasan.builder.BuilderFactory builderFactory;

@org.springframework.context.annotation.Bean
public org.ikasan.spec.module.Module myModule()
{
// Create a module builder from the builder factory
org.ikasan.builder.ModuleBuilder moduleBuilder = builderFactory.getModuleBuilder("My Integration Module")
.withDescription("My first integration module.");

// Create a component builder from the builder factory
org.ikasan.builder.component.ComponentBuilder componentBuilder = builderFactory.getComponentBuilder();

// Add the created flow to the module builder and create the module
org.ikasan.spec.module.Module module = moduleBuilder
.addFlow(get_NewFlow1(moduleBuilder, componentBuilder))
.build();
return module;
}

private org.ikasan.spec.flow.Flow get_NewFlow1(org.ikasan.builder.ModuleBuilder moduleBuilder, ComponentBuilder componentBuilder) {
FlowBuilder NewFlow1FlowBuilder = moduleBuilder.getFlowBuilder("Event Generating Flow");
Flow NewFlow1 = NewFlow1FlowBuilder
.consumer("My Source Consumer", componentBuilder.eventGeneratingConsumer())
.producer("My Target Producer", componentBuilder.logProducer())
.build();
return NewFlow1;
}
}