/**
 * This is the Spring book start class.
 * This file is auto-generated by Ikasan Studio, do no edit.
 */
package org.ikasan.studio;

import org.ikasan.spec.component.transformation.Converter;
import org.ikasan.spec.component.transformation.TransformationException;

public class MyConverter implements Converter<java.lang.String,java.lang.Integer>
{
public java.lang.Integer convert(java.lang.String payload) throws TransformationException
{
return java.lang.Integer.valueOf(payload);
}
}