/**
* Encapsulate the create of a flow
* This file is auto-generated by Ikasan Studio, do no edit.
*/
public class Myflow1 {
@javax.annotation.Resource
org.ikasan.builder.BuilderFactory builderFactory;

@org.springframework.context.annotation.Bean
public org.ikasan.spec.flow.Flow MyFlow1()
{
org.ikasan.builder.ModuleBuilder moduleBuilder = builderFactory.getModuleBuilder("New Module");
org.ikasan.builder.FlowBuilder flowBuilder = moduleBuilder.getFlowBuilder("MyFlow1");
org.ikasan.builder.component.ComponentBuilder componentBuilder = builderFactory.getComponentBuilder();

org.ikasan.spec.flow.Flow myflow1 = flowBuilder
.build();
return myflow1;
}
}