package org.ikasan.studio.component.utils;

/**
* Attempt to copy a payload for debugging using serialisation or reflection.
* Copying is best-effort: reflection copies fields shallowly and failure returns the original object.
* Inspect the result without mutating it, because it may share state with the live flow payload.
* This file is auto-generated by Ikasan Studio, do no edit.
*/
public class DeepCopyUtil {
    /**
     * Attempt to deep copy the supplied Object either by serialisation or reflection
     * @param original object to be duplicated
     * @return either a copy of the object or a reference to the object if copying was not possible
     * @param <T> type of object to be duplicated
     */
    @SuppressWarnings("unchecked")
    public static <T> T deepCopy(T original) {
        if (original != null) {
            if (original instanceof java.io.Serializable) {
                try {
                    byte[] bytes;
                    try (java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
                         java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(baos)) {
                        oos.writeObject(original);
                        oos.flush();
                        bytes = baos.toByteArray();
                    }
                    try (java.io.ObjectInputStream ois = new java.io.ObjectInputStream(
                            new java.io.ByteArrayInputStream(bytes))) {
                        return (T) ois.readObject();
                    }
                } catch (java.io.IOException | ClassNotFoundException e) {
                    return original;
                }
            } else {
                T copy;
                try {
                    copy = (T) original.getClass().getDeclaredConstructor().newInstance();
                } catch (NoSuchMethodException | java.lang.reflect.InvocationTargetException | IllegalAccessException | InstantiationException e) {
                    return original;
                }
                try {
                    for (java.lang.reflect.Field field : original.getClass().getDeclaredFields()) {
                        field.setAccessible(true);
                        field.set(copy, field.get(original));
                    }
                } catch (IllegalAccessException e) {
                    return original;
                }
                return copy;
            }
        }
        return original;
    }
}