/**
 * The studio model section should reflect only the ikasan flow details, so in theory we can take as input the json
 * model generated by Mick's dashboard. All presentation details e.g. icons etc, should be limited to the UI model
 * which will contain references to these elements.
 */
package org.ikasan.studio.model.ikasan;