package org.ikasan.studio.ui.actions;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.ikasan.studio.core.StudioBuildUtils;
import org.ikasan.studio.core.model.ikasan.instance.Module;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.Base64;
import java.util.Map;

/**
 * Shared HTTP client for POSTing to a running module's /studio/inject/{flowName} endpoint (generated by
 * StudioInjectControllerTemplate), used by both SendTestMessageAction (a user-supplied payload) and
 * TriggerScheduledConsumerAction (no payload - just fire the flow now). Kept in one place since the URL
 * construction (module name -> context path, port defaulting, percent-encoding of the flow name) and default
 * credentials are easy to let drift out of sync between the two callers.
 */
final class StudioInjectClient {
    static final Duration HTTP_TIMEOUT = Duration.ofSeconds(5);
    // Ikasan's default seeded admin user (see overwriteDBCreation.sql in ikasan-h2-standalone-persistence),
    // granted the ALL authority so it can reach any endpoint. If a module's admin password has been changed
    // from the default, this will fail with a 401 - callers handle that status explicitly.
    private static final String DEFAULT_CREDENTIALS = "admin:admin";

    private StudioInjectClient() {
    }

    static HttpResponse<String> postPayload(Module module, String flowName, String payload) throws Exception {
        String port = module.getPort() != null ? module.getPort() : "8080";
        // The generated app sets server.servlet.context-path to the module's name (see propertiesTemplate_en.ftl),
        // so every endpoint lives under /<module-name>/... - the same transform (StudioBuildUtils.toUrlString)
        // must be used here to match it exactly. Flow names can contain spaces/other characters that aren't
        // valid raw path characters (e.g. "flow 1") - the multi-arg URI constructor percent-encodes the path
        // for us, unlike URI.create(String), which throws on illegal characters.
        String contextPath = "/" + StudioBuildUtils.toUrlString(module.getIdentity());
        URI uri = new URI("http", null, "localhost", Integer.parseInt(port), contextPath + "/studio/inject/" + flowName, null, null);

        ObjectMapper objectMapper = new ObjectMapper();
        String requestBody = objectMapper.writeValueAsString(Map.of("payload", payload));

        HttpClient client = HttpClient.newBuilder()
                .connectTimeout(HTTP_TIMEOUT)
                .build();
        String credentials = Base64.getEncoder().encodeToString(DEFAULT_CREDENTIALS.getBytes(StandardCharsets.UTF_8));
        HttpRequest request = HttpRequest.newBuilder()
                .uri(uri)
                .timeout(HTTP_TIMEOUT)
                .header("Content-Type", "application/json")
                .header("Authorization", "Basic " + credentials)
                .POST(HttpRequest.BodyPublishers.ofString(requestBody))
                .build();
        return client.send(request, HttpResponse.BodyHandlers.ofString());
    }
}
