package org.ikasan;

/**
* The component factory defines the details of the components and their configuration.
*
* This file is auto-generated by Ikasan Studio, do no edit.
*/
@org.springframework.context.annotation.Configuration
public class ComponentFactoryMyFlow1
{
@org.springframework.beans.factory.annotation.Value("${module.name}")
private String moduleName;

@javax.annotation.Resource
org.ikasan.builder.BuilderFactory builderFactory;

@org.springframework.beans.factory.annotation.Value("${myflow1.file.consumer.cron-expression}")
java.lang.String myFlow1FileConsumerCronexpression;
@org.springframework.beans.factory.annotation.Value("#{${myflow1.file.consumer.filenames}}")
java.util.List<String> myFlow1FileConsumerFilenames;
@javax.annotation.Resource
org.ikasan.component.endpoint.filesystem.messageprovider.FileConsumerConfiguration orgIkasanMyflowConfiguration;
@javax.annotation.Resource
org.ikasan.component.endpoint.quartz.consumer.MessageProvider orgIkasanMyflowMyMessageProvider;
@javax.annotation.Resource
org.ikasan.component.endpoint.filesystem.messageprovider.MessageProviderPostProcessor orgIkasanMyflowMyMssageProviderPostProcessor;
@javax.annotation.Resource
org.ikasan.spec.event.ManagedEventIdentifierService orgIkasanMyflowMyEventService;
@javax.annotation.Resource
org.ikasan.spec.event.EventFactory orgIkasanMyflowMyEventFactory;

public org.ikasan.spec.component.endpoint.Consumer getMyLocalFileConsumer() {
return builderFactory.getComponentBuilder().localFileConsumer()
.setCriticalOnStartup(true)
.setEager(true)
.setConfiguration(orgIkasanMyflowConfiguration)
.setTimezone(UTC)
.setDirectoryDepth(1)
.setConfiguredResourceId("bob")
.setLogMatchedFilenames(true)
.setIgnoreFileRenameWhilstScanning(true)
.setEncoding(UTF-8)
.setSortByModifiedDateTime(true)
.setIgnoreMisfire(true)
.setMessageProvider(orgIkasanMyflowMyMessageProvider)
.setCronExpression(myFlow1FileConsumerCronexpression)
.setSortAscending(true)
.setFilenames(myFlow1FileConsumerFilenames)
.setMessageProviderPostProcessor(orgIkasanMyflowMyMssageProviderPostProcessor)
.setIncludeTrailer(true)
.setMaxEagerCallbacks(1)
.setManagedEventIdentifierService(orgIkasanMyflowMyEventService)
.setEventFactory(orgIkasanMyflowMyEventFactory)
.setIncludeHeader(true)
.build();
}}