package org.ikasan;

/**
* The component factory defines the details of the components and their configuration.
*
* This file is auto-generated by Ikasan Studio, do no edit.
*/
@org.springframework.context.annotation.Configuration
public class ComponentFactoryMyFlow1
{
@org.springframework.beans.factory.annotation.Value("${module.name}")
private String moduleName;

@javax.annotation.Resource
org.ikasan.builder.BuilderFactory builderFactory;

@org.springframework.beans.factory.annotation.Value("#{${myflow1.file.consumer.filenames}}")
java.util.List<String> myFlow1FileConsumerFilenames;
@org.springframework.beans.factory.annotation.Value("${myflow1.file.consumer.cron-expression}")
java.lang.String myFlow1FileConsumerCronexpression;
@javax.annotation.Resource
org.ikasan.spec.event.EventFactory myEventFactoryClassName;
@javax.annotation.Resource
org.ikasan.component.endpoint.quartz.consumer.MessageProvider myMessageProviderClass;
@javax.annotation.Resource
org.ikasan.component.endpoint.filesystem.messageprovider.MessageProviderPostProcessor myMessageProviderPostProcessor;
@javax.annotation.Resource
org.ikasan.component.endpoint.filesystem.messageprovider.FileConsumerConfiguration myConfigurationClass;
@javax.annotation.Resource
org.ikasan.spec.management.ManagedResourceRecoveryManager myManagedResourceRecoveryManagerClass;

public org.ikasan.spec.component.endpoint.Consumer getTestLocalFileConsumer() {
return builderFactory.getComponentBuilder().fileConsumer()
.setEventFactory(myEventFactoryClassName)
.setMessageProvider(myMessageProviderClass)
.setMessageProviderPostProcessor(myMessageProviderPostProcessor)
.setCriticalOnStartup(true)
.setSortByModifiedDateTime(12)
.setConfiguration(myConfigurationClass)
.setScheduledJobName("myScheduledJobName")
.setFilenames(myFlow1FileConsumerFilenames)
.setEager(true)
.setSortAscending(true)
.setCronExpression(myFlow1FileConsumerCronexpression)
.setMaxEagerCallbacks(1)
.setDirectoryDepth(1)
.setScheduledJobGroupName("myScheduledJobGroupName")
.setTimezone("GMT")
.setEncoding("UTF-8")
.setIgnoreFileRenameWhilstScanning(true)
.setIgnoreMisfire(true)
.setManagedResourceRecoveryManager(myManagedResourceRecoveryManagerClass)
.setConfiguredResourceId("myUniqueConfiguredResourceIdName")
.build();
}}