package org.ikasan;

/**
* The component factory defines the details of the components and their configuration.
*
* This file is auto-generated by Ikasan Studio, do no edit.
*/
@org.springframework.context.annotation.Configuration
public class ComponentFactoryMyFlow1
{
@org.springframework.beans.factory.annotation.Value("${module.name}")
private String moduleName;

@javax.annotation.Resource
org.ikasan.builder.BuilderFactory builderFactory;


@javax.annotation.Resource
org.ikasan.component.endpoint.filesystem.messageprovider.FileConsumerConfiguration myConfigurationClass;
@javax.annotation.Resource
java.util.Map<Class, javax.xml.bind.annotation.adapters.XmlAdapter> myXmlAdapterMap;

public org.ikasan.spec.component.transformation.Converter getMyObjectMessageToXMLStringConverter() {
.setConfiguration(myConfigurationClass)
.setConfiguredResourceId("myUniqueConfiguredResourceIdName")
.setFastFailOnConfigurationLoad(true)
.setNamespacePrefix(myNamespacePrefix)
.setNamespaceURI(myNamespaceURI)
.setNoNamespaceSchema(true)
.setObjectClasses(class java.lang.String)
.setObjectClasses({'String.class','String.class'})
.setRootClassName(java.lang.String)
.setRootName(myRootName)
.setRouteOnValidationException(true)
.setSchema(mySchema)
.setSchemaLocation(http://foo.com/domain example.xsd)
.setUseNamespacePrefix(true)
.setValidate(true)
.setXmlAdapterMap(myXmlAdapterMap)
return new org.ikasan.builder.component.converter.ObjectToXmlStringConverterBuilder();
}}